export type Flashcard = {
  id:  number;
   "zh":  string;
   "pinyin":  string;
   "thaiPronunciation":  string;
   "th":  string;
   "thToZh":  string;
   "sentenceZh":  string;
   "sentencePinyin":  string;
   "sentenceThaiPronunciation":  string;
   "sentenceTh":  string;
   "image":  string;
   "category":  "HSK4"};

export const hsk4Data: Flashcard[] = [
  {
    "id": 1,
    "zh": "爱情",
    "pinyin": "ài qíng",
    "thaiPronunciation": "่าอี ชอี๋ng",
    "th": "ความรัก",
    "thToZh": "爱情",
    "sentenceZh": "老师让我们学习“爱情”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “爱情” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 爱情 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ความรัก”",
    "image": "❤️",
    "category": "HSK4"
  },
  {
    "id": 2,
    "zh": "安排",
    "pinyin": "ān pái",
    "thaiPronunciation": "าn ผ๋าอี",
    "th": "จัดการ / วางแผน",
    "thToZh": "安排",
    "sentenceZh": "老师让我们学习“安排”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “安排” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 安排 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “จัดการ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 3,
    "zh": "安全",
    "pinyin": "ān quán",
    "thaiPronunciation": "าn ชอู๋าn",
    "th": "ปลอดภัย / ความปลอดภัย",
    "thToZh": "安全",
    "sentenceZh": "老师让我们学习“安全”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “安全” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 安全 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ปลอดภัย”",
    "image": "🛡️",
    "category": "HSK4"
  },
  {
    "id": 4,
    "zh": "按时",
    "pinyin": "àn shí",
    "thaiPronunciation": "่าn ซอี๋",
    "th": "ตรงเวลา",
    "thToZh": "按时",
    "sentenceZh": "老师让我们学习“按时”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “按时” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 按时 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ตรงเวลา”",
    "image": "⏰",
    "category": "HSK4"
  },
  {
    "id": 5,
    "zh": "按照",
    "pinyin": "àn zhào",
    "thaiPronunciation": "่าn จ่าโอ",
    "th": "ตาม / ตามที่",
    "thToZh": "按照",
    "sentenceZh": "老师让我们学习“按照”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “按照” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 按照 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ตาม”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 6,
    "zh": "百分之",
    "pinyin": "bǎi fēn zhī",
    "thaiPronunciation": "ปา̌อี ฝเออn จอี",
    "th": "เปอร์เซ็นต์",
    "thToZh": "百分之",
    "sentenceZh": "老师让我们学习“百分之”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “百分之” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 百分之 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “เปอร์เซ็นต์”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 7,
    "zh": "棒",
    "pinyin": "bàng",
    "thaiPronunciation": "ป่าng",
    "th": "เยี่ยม / เก่ง",
    "thToZh": "棒",
    "sentenceZh": "老师让我们学习“棒”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “棒” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 棒 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “เยี่ยม”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 8,
    "zh": "包子",
    "pinyin": "bāo zi",
    "thaiPronunciation": "ปาโอ จอี",
    "th": "ซาลาเปา",
    "thToZh": "包子",
    "sentenceZh": "老师让我们学习“包子”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “包子” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 包子 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ซาลาเปา”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 9,
    "zh": "保护",
    "pinyin": "bǎo hù",
    "thaiPronunciation": "ปา̌โอ ฮอู้",
    "th": "ปกป้อง / คุ้มครอง",
    "thToZh": "保护",
    "sentenceZh": "老师让我们学习“保护”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “保护” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 保护 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ปกป้อง”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 10,
    "zh": "保证",
    "pinyin": "bǎo zhèng",
    "thaiPronunciation": "ปา̌โอ จเอ่อng",
    "th": "รับประกัน",
    "thToZh": "保证",
    "sentenceZh": "老师让我们学习“保证”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “保证” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 保证 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “รับประกัน”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 11,
    "zh": "报名",
    "pinyin": "bào míng",
    "thaiPronunciation": "ป่าโอ มอี๋ng",
    "th": "สมัคร / ลงทะเบียน",
    "thToZh": "报名",
    "sentenceZh": "老师让我们学习“报名”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “报名” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 报名 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “สมัคร”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 12,
    "zh": "抱",
    "pinyin": "bào",
    "thaiPronunciation": "ป่าโอ",
    "th": "กอด / อุ้ม",
    "thToZh": "抱",
    "sentenceZh": "老师让我们学习“抱”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “抱” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 抱 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “กอด”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 13,
    "zh": "抱歉",
    "pinyin": "bào qiàn",
    "thaiPronunciation": "ป่าโอ ชอี่าn",
    "th": "ขอโทษ",
    "thToZh": "抱歉",
    "sentenceZh": "老师让我们学习“抱歉”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “抱歉” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 抱歉 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ขอโทษ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 14,
    "zh": "倍",
    "pinyin": "bèi",
    "thaiPronunciation": "ปเอ่ออี",
    "th": "เท่า / เท่าตัว",
    "thToZh": "倍",
    "sentenceZh": "老师让我们学习“倍”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “倍” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 倍 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “เท่า”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 15,
    "zh": "本来",
    "pinyin": "běn lái",
    "thaiPronunciation": "ปเออn ล๋าอี",
    "th": "เดิมที / แต่แรก",
    "thToZh": "本来",
    "sentenceZh": "老师让我们学习“本来”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “本来” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 本来 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “เดิมที”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 16,
    "zh": "笨",
    "pinyin": "bèn",
    "thaiPronunciation": "ปเอ่อn",
    "th": "โง่ / ทึ่ม",
    "thToZh": "笨",
    "sentenceZh": "老师让我们学习“笨”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “笨” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 笨 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “โง่”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 17,
    "zh": "比如",
    "pinyin": "bǐ rú",
    "thaiPronunciation": "ปอี รอู๋",
    "th": "เช่น / ตัวอย่างเช่น",
    "thToZh": "比如",
    "sentenceZh": "老师让我们学习“比如”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “比如” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 比如 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “เช่น”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 18,
    "zh": "毕业",
    "pinyin": "bì yè",
    "thaiPronunciation": "ปอี้ ยเอ่อ",
    "th": "เรียนจบ",
    "thToZh": "毕业",
    "sentenceZh": "老师让我们学习“毕业”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “毕业” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 毕业 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “เรียนจบ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 19,
    "zh": "遍",
    "pinyin": "biàn",
    "thaiPronunciation": "ปอี่าn",
    "th": "รอบ / ครั้ง",
    "thToZh": "遍",
    "sentenceZh": "老师让我们学习“遍”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “遍” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 遍 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “รอบ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 20,
    "zh": "标准",
    "pinyin": "biāo zhǔn",
    "thaiPronunciation": "ปอีาโอ จอูn",
    "th": "มาตรฐาน",
    "thToZh": "标准",
    "sentenceZh": "老师让我们学习“标准”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “标准” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 标准 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “มาตรฐาน”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 21,
    "zh": "表格",
    "pinyin": "biǎo gé",
    "thaiPronunciation": "ปอีา̌โอ กเอ๋อ",
    "th": "แบบฟอร์ม / ตาราง",
    "thToZh": "表格",
    "sentenceZh": "老师让我们学习“表格”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “表格” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 表格 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “แบบฟอร์ม”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 22,
    "zh": "表示",
    "pinyin": "biǎo shì",
    "thaiPronunciation": "ปอีา̌โอ ซอี้",
    "th": "แสดง / บอก",
    "thToZh": "表示",
    "sentenceZh": "老师让我们学习“表示”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “表示” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 表示 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “แสดง”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 23,
    "zh": "表演",
    "pinyin": "biǎo yǎn",
    "thaiPronunciation": "ปอีา̌โอ ยา̌n",
    "th": "แสดง",
    "thToZh": "表演",
    "sentenceZh": "老师让我们学习“表演”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “表演” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 表演 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “แสดง”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 24,
    "zh": "表扬",
    "pinyin": "biǎo yáng",
    "thaiPronunciation": "ปอีา̌โอ ย๋าng",
    "th": "ชมเชย",
    "thToZh": "表扬",
    "sentenceZh": "老师让我们学习“表扬”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “表扬” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 表扬 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ชมเชย”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 25,
    "zh": "饼干",
    "pinyin": "bǐng gān",
    "thaiPronunciation": "ปอีng กาn",
    "th": "บิสกิต / คุกกี้",
    "thToZh": "饼干",
    "sentenceZh": "老师让我们学习“饼干”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “饼干” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 饼干 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “บิสกิต”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 26,
    "zh": "并且",
    "pinyin": "bìng qiě",
    "thaiPronunciation": "ปอี้ng ชอีเออ",
    "th": "และ / อีกทั้ง",
    "thToZh": "并且",
    "sentenceZh": "老师让我们学习“并且”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “并且” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 并且 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “และ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 27,
    "zh": "博士",
    "pinyin": "bó shì",
    "thaiPronunciation": "ปโอ๋ ซอี้",
    "th": "ปริญญาเอก / ดอกเตอร์",
    "thToZh": "博士",
    "sentenceZh": "老师让我们学习“博士”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “博士” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 博士 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ปริญญาเอก”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 28,
    "zh": "不过",
    "pinyin": "bú guò",
    "thaiPronunciation": "ปอู๋ กอูโอ้",
    "th": "แต่ว่า / อย่างไรก็ตาม",
    "thToZh": "不过",
    "sentenceZh": "老师让我们学习“不过”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “不过” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 不过 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “แต่ว่า”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 29,
    "zh": "不得不",
    "pinyin": "bù dé bù",
    "thaiPronunciation": "ปอู้ ตเอ๋อ ปอู้",
    "th": "จำเป็นต้อง",
    "thToZh": "不得不",
    "sentenceZh": "老师让我们学习“不得不”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “不得不” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 不得不 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “จำเป็นต้อง”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 30,
    "zh": "不管",
    "pinyin": "bù guǎn",
    "thaiPronunciation": "ปอู้ กอูา̌n",
    "th": "ไม่ว่า",
    "thToZh": "不管",
    "sentenceZh": "老师让我们学习“不管”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “不管” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 不管 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ไม่ว่า”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 31,
    "zh": "不仅",
    "pinyin": "bù jǐn",
    "thaiPronunciation": "ปอู้ จอีn",
    "th": "ไม่เพียงแต่",
    "thToZh": "不仅",
    "sentenceZh": "老师让我们学习“不仅”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “不仅” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 不仅 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ไม่เพียงแต่”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 32,
    "zh": "部分",
    "pinyin": "bù fen",
    "thaiPronunciation": "ปอู้ ฝเอิน",
    "th": "ส่วนหนึ่ง / บางส่วน",
    "thToZh": "部分",
    "sentenceZh": "老师让我们学习“部分”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “部分” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 部分 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ส่วนหนึ่ง”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 33,
    "zh": "擦",
    "pinyin": "cā",
    "thaiPronunciation": "ชา",
    "th": "เช็ด",
    "thToZh": "擦",
    "sentenceZh": "老师让我们学习“擦”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “擦” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 擦 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “เช็ด”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 34,
    "zh": "猜",
    "pinyin": "cāi",
    "thaiPronunciation": "ชาอี",
    "th": "เดา",
    "thToZh": "猜",
    "sentenceZh": "老师让我们学习“猜”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “猜” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 猜 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “เดา”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 35,
    "zh": "材料",
    "pinyin": "cái liào",
    "thaiPronunciation": "ช๋าอี ลอี่าโอ",
    "th": "วัสดุ / ข้อมูล",
    "thToZh": "材料",
    "sentenceZh": "老师让我们学习“材料”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “材料” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 材料 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “วัสดุ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 36,
    "zh": "参观",
    "pinyin": "cān guān",
    "thaiPronunciation": "ชาn กอูาn",
    "th": "เยี่ยมชม",
    "thToZh": "参观",
    "sentenceZh": "老师让我们学习“参观”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “参观” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 参观 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “เยี่ยมชม”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 37,
    "zh": "餐厅",
    "pinyin": "cān tīng",
    "thaiPronunciation": "ชาn ทอีng",
    "th": "ร้านอาหาร",
    "thToZh": "餐厅",
    "sentenceZh": "老师让我们学习“餐厅”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “餐厅” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 餐厅 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ร้านอาหาร”",
    "image": "🍽️",
    "category": "HSK4"
  },
  {
    "id": 38,
    "zh": "厕所",
    "pinyin": "cè suǒ",
    "thaiPronunciation": "ชเอ่อ สอูโอ",
    "th": "ห้องน้ำ",
    "thToZh": "厕所",
    "sentenceZh": "老师让我们学习“厕所”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “厕所” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 厕所 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ห้องน้ำ”",
    "image": "🚻",
    "category": "HSK4"
  },
  {
    "id": 39,
    "zh": "差不多",
    "pinyin": "chà bu duō",
    "thaiPronunciation": "ช่า ปอู ตอูโอ",
    "th": "เกือบ / พอๆ กัน",
    "thToZh": "差不多",
    "sentenceZh": "老师让我们学习“差不多”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “差不多” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 差不多 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “เกือบ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 40,
    "zh": "尝",
    "pinyin": "cháng",
    "thaiPronunciation": "ช๋าng",
    "th": "ลองชิม / ลอง",
    "thToZh": "尝",
    "sentenceZh": "老师让我们学习“尝”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “尝” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 尝 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ลองชิม”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 41,
    "zh": "长城",
    "pinyin": "cháng chéng",
    "thaiPronunciation": "ช๋าng ชเอ๋อng",
    "th": "กำแพงเมืองจีน",
    "thToZh": "长城",
    "sentenceZh": "老师让我们学习“长城”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “长城” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 长城 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “กำแพงเมืองจีน”",
    "image": "🧱",
    "category": "HSK4"
  },
  {
    "id": 42,
    "zh": "长江",
    "pinyin": "cháng jiāng",
    "thaiPronunciation": "ช๋าng จอีาng",
    "th": "แม่น้ำแยงซี",
    "thToZh": "长江",
    "sentenceZh": "老师让我们学习“长江”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “长江” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 长江 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “แม่น้ำแยงซี”",
    "image": "🌊",
    "category": "HSK4"
  },
  {
    "id": 43,
    "zh": "场",
    "pinyin": "chǎng",
    "thaiPronunciation": "ชา̌ng",
    "th": "สนาม / งาน / รอบ",
    "thToZh": "场",
    "sentenceZh": "老师让我们学习“场”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “场” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 场 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “สนาม”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 44,
    "zh": "超过",
    "pinyin": "chāo guò",
    "thaiPronunciation": "ชาโอ กอูโอ้",
    "th": "เกิน / เกินกว่า",
    "thToZh": "超过",
    "sentenceZh": "老师让我们学习“超过”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “超过” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 超过 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “เกิน”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 45,
    "zh": "乘坐",
    "pinyin": "chéng zuò",
    "thaiPronunciation": "ชเอ๋อng จอูโอ้",
    "th": "นั่ง / โดยสาร",
    "thToZh": "乘坐",
    "sentenceZh": "老师让我们学习“乘坐”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “乘坐” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 乘坐 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “นั่ง”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 46,
    "zh": "成功",
    "pinyin": "chéng gōng",
    "thaiPronunciation": "ชเอ๋อng กโอng",
    "th": "สำเร็จ",
    "thToZh": "成功",
    "sentenceZh": "老师让我们学习“成功”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “成功” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 成功 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “สำเร็จ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 47,
    "zh": "成为",
    "pinyin": "chéng wéi",
    "thaiPronunciation": "ชเอ๋อng วเอ๋ออี",
    "th": "กลายเป็น",
    "thToZh": "成为",
    "sentenceZh": "老师让我们学习“成为”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “成为” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 成为 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “กลายเป็น”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 48,
    "zh": "诚实",
    "pinyin": "chéng shí",
    "thaiPronunciation": "ชเอ๋อng ซอี๋",
    "th": "ซื่อสัตย์",
    "thToZh": "诚实",
    "sentenceZh": "老师让我们学习“诚实”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “诚实” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 诚实 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ซื่อสัตย์”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 49,
    "zh": "吃惊",
    "pinyin": "chī jīng",
    "thaiPronunciation": "ชอี จอีng",
    "th": "ตกใจ",
    "thToZh": "吃惊",
    "sentenceZh": "老师让我们学习“吃惊”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “吃惊” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 吃惊 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ตกใจ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 50,
    "zh": "重新",
    "pinyin": "chóng xīn",
    "thaiPronunciation": "ชโอ๋ng ซอีn",
    "th": "อีกครั้ง / ใหม่อีกครั้ง",
    "thToZh": "重新",
    "sentenceZh": "老师让我们学习“重新”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “重新” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 重新 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “อีกครั้ง”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 51,
    "zh": "抽烟",
    "pinyin": "chōu yān",
    "thaiPronunciation": "ชโออู ยาn",
    "th": "สูบบุหรี่",
    "thToZh": "抽烟",
    "sentenceZh": "老师让我们学习“抽烟”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “抽烟” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 抽烟 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “สูบบุหรี่”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 52,
    "zh": "出差",
    "pinyin": "chū chāi",
    "thaiPronunciation": "ชอู ชาอี",
    "th": "เดินทางไปทำงานต่างที่",
    "thToZh": "出差",
    "sentenceZh": "老师让我们学习“出差”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “出差” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 出差 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “เดินทางไปทำงานต่างที่”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 53,
    "zh": "出发",
    "pinyin": "chū fā",
    "thaiPronunciation": "ชอู ฝา",
    "th": "ออกเดินทาง",
    "thToZh": "出发",
    "sentenceZh": "老师让我们学习“出发”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “出发” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 出发 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ออกเดินทาง”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 54,
    "zh": "出生",
    "pinyin": "chū shēng",
    "thaiPronunciation": "ชอู ซเออng",
    "th": "เกิด",
    "thToZh": "出生",
    "sentenceZh": "老师让我们学习“出生”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “出生” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 出生 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “เกิด”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 55,
    "zh": "出现",
    "pinyin": "chū xiàn",
    "thaiPronunciation": "ชอู ซอี่าn",
    "th": "ปรากฏ / เกิดขึ้น",
    "thToZh": "出现",
    "sentenceZh": "老师让我们学习“出现”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “出现” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 出现 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ปรากฏ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 56,
    "zh": "厨房",
    "pinyin": "chú fáng",
    "thaiPronunciation": "ชอู๋ ฝ๋าng",
    "th": "ห้องครัว",
    "thToZh": "厨房",
    "sentenceZh": "老师让我们学习“厨房”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “厨房” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 厨房 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ห้องครัว”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 57,
    "zh": "传真",
    "pinyin": "chuán zhēn",
    "thaiPronunciation": "ชอู๋าn จเออn",
    "th": "แฟกซ์",
    "thToZh": "传真",
    "sentenceZh": "老师让我们学习“传真”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “传真” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 传真 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “แฟกซ์”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 58,
    "zh": "窗户",
    "pinyin": "chuāng hu",
    "thaiPronunciation": "ชอูาng ฮอู",
    "th": "หน้าต่าง",
    "thToZh": "窗户",
    "sentenceZh": "老师让我们学习“窗户”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “窗户” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 窗户 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “หน้าต่าง”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 59,
    "zh": "词语",
    "pinyin": "cí yǔ",
    "thaiPronunciation": "ชอี๋ ยอู",
    "th": "คำศัพท์ / วลี",
    "thToZh": "词语",
    "sentenceZh": "老师让我们学习“词语”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “词语” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 词语 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “คำศัพท์”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 60,
    "zh": "从来",
    "pinyin": "cóng lái",
    "thaiPronunciation": "ชโอ๋ng ล๋าอี",
    "th": "เสมอมา / ไม่เคย(ในประโยคปฏิเสธ)",
    "thToZh": "从来",
    "sentenceZh": "老师让我们学习“从来”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “从来” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 从来 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “เสมอมา”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 61,
    "zh": "粗心",
    "pinyin": "cū xīn",
    "thaiPronunciation": "ชอู ซอีn",
    "th": "สะเพร่า",
    "thToZh": "粗心",
    "sentenceZh": "老师让我们学习“粗心”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “粗心” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 粗心 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “สะเพร่า”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 62,
    "zh": "存",
    "pinyin": "cún",
    "thaiPronunciation": "ชอู๋n",
    "th": "เก็บ / ฝาก / มีอยู่",
    "thToZh": "存",
    "sentenceZh": "老师让我们学习“存”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “存” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 存 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “เก็บ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 63,
    "zh": "错误",
    "pinyin": "cuò wù",
    "thaiPronunciation": "ชอูโอ้ วอู้",
    "th": "ข้อผิดพลาด",
    "thToZh": "错误",
    "sentenceZh": "老师让我们学习“错误”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “错误” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 错误 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ข้อผิดพลาด”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 64,
    "zh": "答案",
    "pinyin": "dá àn",
    "thaiPronunciation": "ต๋า ่าn",
    "th": "คำตอบ",
    "thToZh": "答案",
    "sentenceZh": "老师让我们学习“答案”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “答案” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 答案 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “คำตอบ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 65,
    "zh": "打扮",
    "pinyin": "dǎ ban",
    "thaiPronunciation": "ตา̌ ปอัน",
    "th": "แต่งตัว",
    "thToZh": "打扮",
    "sentenceZh": "老师让我们学习“打扮”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “打扮” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 打扮 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “แต่งตัว”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 66,
    "zh": "打扰",
    "pinyin": "dǎ rǎo",
    "thaiPronunciation": "ตา̌ รา̌โอ",
    "th": "รบกวน",
    "thToZh": "打扰",
    "sentenceZh": "老师让我们学习“打扰”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “打扰” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 打扰 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “รบกวน”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 67,
    "zh": "打印",
    "pinyin": "dǎ yìn",
    "thaiPronunciation": "ตา̌ ยอี้n",
    "th": "พิมพ์",
    "thToZh": "打印",
    "sentenceZh": "老师让我们学习“打印”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “打印” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 打印 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “พิมพ์”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 68,
    "zh": "打招呼",
    "pinyin": "dǎ zhāo hu",
    "thaiPronunciation": "ตา̌ จาโอ ฮอู",
    "th": "ทักทาย",
    "thToZh": "打招呼",
    "sentenceZh": "老师让我们学习“打招呼”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “打招呼” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 打招呼 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ทักทาย”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 69,
    "zh": "打折",
    "pinyin": "dǎ zhé",
    "thaiPronunciation": "ตา̌ จเอ๋อ",
    "th": "ลดราคา",
    "thToZh": "打折",
    "sentenceZh": "老师让我们学习“打折”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “打折” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 打折 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ลดราคา”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 70,
    "zh": "打针",
    "pinyin": "dǎ zhēn",
    "thaiPronunciation": "ตา̌ จเออn",
    "th": "ฉีดยา",
    "thToZh": "打针",
    "sentenceZh": "老师让我们学习“打针”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “打针” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 打针 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ฉีดยา”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 71,
    "zh": "大概",
    "pinyin": "dà gài",
    "thaiPronunciation": "ต่า ก่าอี",
    "th": "ประมาณ / น่าจะ",
    "thToZh": "大概",
    "sentenceZh": "老师让我们学习“大概”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “大概” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 大概 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ประมาณ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 72,
    "zh": "大使馆",
    "pinyin": "dà shǐ guǎn",
    "thaiPronunciation": "ต่า ซอี กอูา̌n",
    "th": "สถานทูต",
    "thToZh": "大使馆",
    "sentenceZh": "老师让我们学习“大使馆”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “大使馆” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 大使馆 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “สถานทูต”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 73,
    "zh": "大约",
    "pinyin": "dà yuē",
    "thaiPronunciation": "ต่า ยอูเออ",
    "th": "ประมาณ",
    "thToZh": "大约",
    "sentenceZh": "老师让我们学习“大约”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “大约” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 大约 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ประมาณ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 74,
    "zh": "大夫",
    "pinyin": "dài fu",
    "thaiPronunciation": "ต่าอี ฝอู",
    "th": "หมอ",
    "thToZh": "大夫",
    "sentenceZh": "老师让我们学习“大夫”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “大夫” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 大夫 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “หมอ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 75,
    "zh": "戴",
    "pinyin": "dài",
    "thaiPronunciation": "ต่าอี",
    "th": "สวม / ใส่",
    "thToZh": "戴",
    "sentenceZh": "老师让我们学习“戴”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “戴” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 戴 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “สวม”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 76,
    "zh": "当",
    "pinyin": "dāng",
    "thaiPronunciation": "ตาng",
    "th": "เป็น / ตอนที่",
    "thToZh": "当",
    "sentenceZh": "老师让我们学习“当”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “当” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 当 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “เป็น”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 77,
    "zh": "当时",
    "pinyin": "dāng shí",
    "thaiPronunciation": "ตาng ซอี๋",
    "th": "ตอนนั้น",
    "thToZh": "当时",
    "sentenceZh": "老师让我们学习“当时”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “当时” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 当时 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ตอนนั้น”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 78,
    "zh": "刀",
    "pinyin": "dāo",
    "thaiPronunciation": "ตาโอ",
    "th": "มีด",
    "thToZh": "刀",
    "sentenceZh": "老师让我们学习“刀”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “刀” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 刀 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “มีด”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 79,
    "zh": "导游",
    "pinyin": "dǎo yóu",
    "thaiPronunciation": "ตา̌โอ ยโอ๋อู",
    "th": "ไกด์ / มัคคุเทศก์",
    "thToZh": "导游",
    "sentenceZh": "老师让我们学习“导游”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “导游” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 导游 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ไกด์”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 80,
    "zh": "倒",
    "pinyin": "dào",
    "thaiPronunciation": "ต่าโอ",
    "th": "กลับด้าน / เทกลับ",
    "thToZh": "倒",
    "sentenceZh": "老师让我们学习“倒”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “倒” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 倒 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “กลับด้าน”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 81,
    "zh": "到处",
    "pinyin": "dào chù",
    "thaiPronunciation": "ต่าโอ ชอู้",
    "th": "ทุกที่",
    "thToZh": "到处",
    "sentenceZh": "老师让我们学习“到处”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “到处” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 到处 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ทุกที่”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 82,
    "zh": "到底",
    "pinyin": "dào dǐ",
    "thaiPronunciation": "ต่าโอ ตอี",
    "th": "ท้ายที่สุด / ตกลงว่า",
    "thToZh": "到底",
    "sentenceZh": "老师让我们学习“到底”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “到底” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 到底 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ท้ายที่สุด”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 83,
    "zh": "道歉",
    "pinyin": "dào qiàn",
    "thaiPronunciation": "ต่าโอ ชอี่าn",
    "th": "ขอโทษ",
    "thToZh": "道歉",
    "sentenceZh": "老师让我们学习“道歉”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “道歉” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 道歉 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ขอโทษ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 84,
    "zh": "得",
    "pinyin": "dé",
    "thaiPronunciation": "ตเอ๋อ",
    "th": "ต้อง / ได้",
    "thToZh": "得",
    "sentenceZh": "老师让我们学习“得”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “得” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 得 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ต้อง”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 85,
    "zh": "得意",
    "pinyin": "dé yì",
    "thaiPronunciation": "ตเอ๋อ ยอี้",
    "th": "ภูมิใจ / ได้ใจ",
    "thToZh": "得意",
    "sentenceZh": "老师让我们学习“得意”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “得意” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 得意 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ภูมิใจ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 86,
    "zh": "登机牌",
    "pinyin": "dēng jī pái",
    "thaiPronunciation": "ตเออng จอี ผ๋าอี",
    "th": "บอร์ดดิ้งพาส",
    "thToZh": "登机牌",
    "sentenceZh": "老师让我们学习“登机牌”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “登机牌” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 登机牌 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “บอร์ดดิ้งพาส”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 87,
    "zh": "等",
    "pinyin": "děng",
    "thaiPronunciation": "ตเออng",
    "th": "ฯลฯ / รอ",
    "thToZh": "等",
    "sentenceZh": "老师让我们学习“等”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “等” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 等 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ฯลฯ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 88,
    "zh": "低",
    "pinyin": "dī",
    "thaiPronunciation": "ตอี",
    "th": "ต่ำ",
    "thToZh": "低",
    "sentenceZh": "老师让我们学习“低”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “低” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 低 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ต่ำ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 89,
    "zh": "底",
    "pinyin": "dǐ",
    "thaiPronunciation": "ตอี",
    "th": "ด้านล่าง / ก้น",
    "thToZh": "底",
    "sentenceZh": "老师让我们学习“底”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “底” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 底 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ด้านล่าง”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 90,
    "zh": "地点",
    "pinyin": "dì diǎn",
    "thaiPronunciation": "ตอี้ ตอีา̌n",
    "th": "สถานที่",
    "thToZh": "地点",
    "sentenceZh": "老师让我们学习“地点”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “地点” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 地点 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “สถานที่”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 91,
    "zh": "地球",
    "pinyin": "dì qiú",
    "thaiPronunciation": "ตอี้ ชอีอู๋",
    "th": "โลก",
    "thToZh": "地球",
    "sentenceZh": "老师让我们学习“地球”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “地球” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 地球 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “โลก”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 92,
    "zh": "地址",
    "pinyin": "dì zhǐ",
    "thaiPronunciation": "ตอี้ จอี",
    "th": "ที่อยู่",
    "thToZh": "地址",
    "sentenceZh": "老师让我们学习“地址”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “地址” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 地址 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ที่อยู่”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 93,
    "zh": "掉",
    "pinyin": "diào",
    "thaiPronunciation": "ตอี่าโอ",
    "th": "ตก / หล่น / หาย",
    "thToZh": "掉",
    "sentenceZh": "老师让我们学习“掉”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “掉” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 掉 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ตก”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 94,
    "zh": "调查",
    "pinyin": "diào chá",
    "thaiPronunciation": "ตอี่าโอ ช๋า",
    "th": "สำรวจ / ตรวจสอบ",
    "thToZh": "调查",
    "sentenceZh": "老师让我们学习“调查”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “调查” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 调查 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “สำรวจ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 95,
    "zh": "丢",
    "pinyin": "diū",
    "thaiPronunciation": "ตอีอู",
    "th": "ทำหาย / ทิ้ง",
    "thToZh": "丢",
    "sentenceZh": "老师让我们学习“丢”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “丢” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 丢 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ทำหาย”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 96,
    "zh": "动作",
    "pinyin": "dòng zuò",
    "thaiPronunciation": "ตโอ้ng จอูโอ้",
    "th": "การเคลื่อนไหว / ท่าทาง",
    "thToZh": "动作",
    "sentenceZh": "老师让我们学习“动作”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “动作” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 动作 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “การเคลื่อนไหว”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 97,
    "zh": "堵车",
    "pinyin": "dǔ chē",
    "thaiPronunciation": "ตอู ชเออ",
    "th": "รถติด",
    "thToZh": "堵车",
    "sentenceZh": "老师让我们学习“堵车”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “堵车” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 堵车 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “รถติด”",
    "image": "🚗",
    "category": "HSK4"
  },
  {
    "id": 98,
    "zh": "肚子",
    "pinyin": "dù zi",
    "thaiPronunciation": "ตอู้ จอี",
    "th": "ท้อง",
    "thToZh": "肚子",
    "sentenceZh": "老师让我们学习“肚子”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “肚子” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 肚子 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ท้อง”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 99,
    "zh": "短信",
    "pinyin": "duǎn xìn",
    "thaiPronunciation": "ตอูา̌n ซอี้n",
    "th": "ข้อความสั้น / SMS",
    "thToZh": "短信",
    "sentenceZh": "老师让我们学习“短信”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “短信” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 短信 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ข้อความสั้น”",
    "image": "💬",
    "category": "HSK4"
  },
  {
    "id": 100,
    "zh": "对话",
    "pinyin": "duì huà",
    "thaiPronunciation": "ตอูอี้ ฮอู่า",
    "th": "บทสนทนา",
    "thToZh": "对话",
    "sentenceZh": "老师让我们学习“对话”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “对话” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 对话 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “บทสนทนา”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 101,
    "zh": "对面",
    "pinyin": "duì miàn",
    "thaiPronunciation": "ตอูอี้ มอี่าn",
    "th": "ตรงข้าม",
    "thToZh": "对面",
    "sentenceZh": "老师让我们学习“对面”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “对面” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 对面 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ตรงข้าม”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 102,
    "zh": "对于",
    "pinyin": "duì yú",
    "thaiPronunciation": "ตอูอี้ ยอู๋",
    "th": "สำหรับ / เกี่ยวกับ",
    "thToZh": "对于",
    "sentenceZh": "老师让我们学习“对于”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “对于” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 对于 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “สำหรับ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 103,
    "zh": "儿童",
    "pinyin": "ér tóng",
    "thaiPronunciation": "เอ๋อr ทโอ๋ng",
    "th": "เด็ก",
    "thToZh": "儿童",
    "sentenceZh": "老师让我们学习“儿童”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “儿童” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 儿童 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “เด็ก”",
    "image": "🧒",
    "category": "HSK4"
  },
  {
    "id": 104,
    "zh": "而",
    "pinyin": "ér",
    "thaiPronunciation": "เอ๋อr",
    "th": "และ / แต่",
    "thToZh": "而",
    "sentenceZh": "老师让我们学习“而”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “而” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 而 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “และ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 105,
    "zh": "发生",
    "pinyin": "fā shēng",
    "thaiPronunciation": "ฝา ซเออng",
    "th": "เกิดขึ้น",
    "thToZh": "发生",
    "sentenceZh": "老师让我们学习“发生”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “发生” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 发生 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “เกิดขึ้น”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 106,
    "zh": "发展",
    "pinyin": "fā zhǎn",
    "thaiPronunciation": "ฝา จา̌n",
    "th": "พัฒนา",
    "thToZh": "发展",
    "sentenceZh": "老师让我们学习“发展”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “发展” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 发展 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “พัฒนา”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 107,
    "zh": "法律",
    "pinyin": "fǎ lǜ",
    "thaiPronunciation": "ฝา̌ ลอวี้",
    "th": "กฎหมาย",
    "thToZh": "法律",
    "sentenceZh": "老师让我们学习“法律”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “法律” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 法律 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “กฎหมาย”",
    "image": "⚖️",
    "category": "HSK4"
  },
  {
    "id": 108,
    "zh": "翻译",
    "pinyin": "fān yì",
    "thaiPronunciation": "ฝาn ยอี้",
    "th": "แปลภาษา",
    "thToZh": "翻译",
    "sentenceZh": "老师让我们学习“翻译”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “翻译” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 翻译 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “แปลภาษา”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 109,
    "zh": "烦恼",
    "pinyin": "fán nǎo",
    "thaiPronunciation": "ฝ๋าn นา̌โอ",
    "th": "ความกังวล / กลุ้มใจ",
    "thToZh": "烦恼",
    "sentenceZh": "老师让我们学习“烦恼”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “烦恼” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 烦恼 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ความกังวล”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 110,
    "zh": "反对",
    "pinyin": "fǎn duì",
    "thaiPronunciation": "ฝา̌n ตอูอี้",
    "th": "คัดค้าน",
    "thToZh": "反对",
    "sentenceZh": "老师让我们学习“反对”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “反对” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 反对 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “คัดค้าน”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 111,
    "zh": "方法",
    "pinyin": "fāng fǎ",
    "thaiPronunciation": "ฝาng ฝา̌",
    "th": "วิธี",
    "thToZh": "方法",
    "sentenceZh": "老师让我们学习“方法”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “方法” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 方法 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “วิธี”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 112,
    "zh": "方面",
    "pinyin": "fāng miàn",
    "thaiPronunciation": "ฝาng มอี่าn",
    "th": "ด้าน / แง่มุม",
    "thToZh": "方面",
    "sentenceZh": "老师让我们学习“方面”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “方面” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 方面 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ด้าน”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 113,
    "zh": "方向",
    "pinyin": "fāng xiàng",
    "thaiPronunciation": "ฝาng ซอี่าng",
    "th": "ทิศทาง",
    "thToZh": "方向",
    "sentenceZh": "老师让我们学习“方向”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “方向” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 方向 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ทิศทาง”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 114,
    "zh": "房东",
    "pinyin": "fáng dōng",
    "thaiPronunciation": "ฝ๋าng ตโอng",
    "th": "เจ้าของบ้าน / เจ้าของห้องเช่า",
    "thToZh": "房东",
    "sentenceZh": "老师让我们学习“房东”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “房东” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 房东 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “เจ้าของบ้าน”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 115,
    "zh": "放弃",
    "pinyin": "fàng qì",
    "thaiPronunciation": "ฝ่าng ชอี้",
    "th": "ยอมแพ้ / ละทิ้ง",
    "thToZh": "放弃",
    "sentenceZh": "老师让我们学习“放弃”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “放弃” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 放弃 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ยอมแพ้”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 116,
    "zh": "放暑假",
    "pinyin": "fàng shǔ jià",
    "thaiPronunciation": "ฝ่าng ซอู จอี่า",
    "th": "ปิดเทอมฤดูร้อน",
    "thToZh": "放暑假",
    "sentenceZh": "老师让我们学习“放暑假”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “放暑假” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 放暑假 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ปิดเทอมฤดูร้อน”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 117,
    "zh": "放松",
    "pinyin": "fàng sōng",
    "thaiPronunciation": "ฝ่าng สโอng",
    "th": "ผ่อนคลาย",
    "thToZh": "放松",
    "sentenceZh": "老师让我们学习“放松”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “放松” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 放松 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ผ่อนคลาย”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 118,
    "zh": "份",
    "pinyin": "fèn",
    "thaiPronunciation": "ฝเอ่อn",
    "th": "ฉบับ / ส่วน / ชุด",
    "thToZh": "份",
    "sentenceZh": "老师让我们学习“份”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “份” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 份 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ฉบับ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 119,
    "zh": "丰富",
    "pinyin": "fēng fù",
    "thaiPronunciation": "ฝเออng ฝอู้",
    "th": "อุดมสมบูรณ์ / หลากหลาย",
    "thToZh": "丰富",
    "sentenceZh": "老师让我们学习“丰富”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “丰富” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 丰富 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “อุดมสมบูรณ์”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 120,
    "zh": "否则",
    "pinyin": "fǒu zé",
    "thaiPronunciation": "ฝโออู จเอ๋อ",
    "th": "มิฉะนั้น",
    "thToZh": "否则",
    "sentenceZh": "老师让我们学习“否则”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “否则” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 否则 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “มิฉะนั้น”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 121,
    "zh": "符合",
    "pinyin": "fú hé",
    "thaiPronunciation": "ฝอู๋ ฮเอ๋อ",
    "th": "สอดคล้อง / ตรงตาม",
    "thToZh": "符合",
    "sentenceZh": "老师让我们学习“符合”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “符合” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 符合 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “สอดคล้อง”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 122,
    "zh": "付款",
    "pinyin": "fù kuǎn",
    "thaiPronunciation": "ฝอู้ คอูา̌n",
    "th": "ชำระเงิน",
    "thToZh": "付款",
    "sentenceZh": "老师让我们学习“付款”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “付款” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 付款 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ชำระเงิน”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 123,
    "zh": "复印",
    "pinyin": "fù yìn",
    "thaiPronunciation": "ฝอู้ ยอี้n",
    "th": "ถ่ายเอกสาร",
    "thToZh": "复印",
    "sentenceZh": "老师让我们学习“复印”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “复印” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 复印 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ถ่ายเอกสาร”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 124,
    "zh": "复杂",
    "pinyin": "fù zá",
    "thaiPronunciation": "ฝอู้ จ๋า",
    "th": "ซับซ้อน",
    "thToZh": "复杂",
    "sentenceZh": "老师让我们学习“复杂”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “复杂” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 复杂 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ซับซ้อน”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 125,
    "zh": "富",
    "pinyin": "fù",
    "thaiPronunciation": "ฝอู้",
    "th": "ร่ำรวย",
    "thToZh": "富",
    "sentenceZh": "老师让我们学习“富”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “富” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 富 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ร่ำรวย”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 126,
    "zh": "父亲",
    "pinyin": "fù qīn",
    "thaiPronunciation": "ฝอู้ ชอีn",
    "th": "พ่อ",
    "thToZh": "父亲",
    "sentenceZh": "老师让我们学习“父亲”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “父亲” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 父亲 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “พ่อ”",
    "image": "👨",
    "category": "HSK4"
  },
  {
    "id": 127,
    "zh": "负责",
    "pinyin": "fù zé",
    "thaiPronunciation": "ฝอู้ จเอ๋อ",
    "th": "รับผิดชอบ",
    "thToZh": "负责",
    "sentenceZh": "老师让我们学习“负责”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “负责” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 负责 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “รับผิดชอบ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 128,
    "zh": "改变",
    "pinyin": "gǎi biàn",
    "thaiPronunciation": "กา̌อี ปอี่าn",
    "th": "เปลี่ยนแปลง",
    "thToZh": "改变",
    "sentenceZh": "老师让我们学习“改变”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “改变” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 改变 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “เปลี่ยนแปลง”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 129,
    "zh": "干杯",
    "pinyin": "gān bēi",
    "thaiPronunciation": "กาn ปเอออี",
    "th": "ชนแก้ว",
    "thToZh": "干杯",
    "sentenceZh": "老师让我们学习“干杯”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “干杯” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 干杯 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ชนแก้ว”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 130,
    "zh": "感动",
    "pinyin": "gǎn dòng",
    "thaiPronunciation": "กา̌n ตโอ้ng",
    "th": "ซาบซึ้ง / ทำให้ประทับใจ",
    "thToZh": "感动",
    "sentenceZh": "老师让我们学习“感动”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “感动” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 感动 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ซาบซึ้ง”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 131,
    "zh": "感觉",
    "pinyin": "gǎn jué",
    "thaiPronunciation": "กา̌n จอูเอ๋อ",
    "th": "ความรู้สึก / รู้สึก",
    "thToZh": "感觉",
    "sentenceZh": "老师让我们学习“感觉”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “感觉” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 感觉 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ความรู้สึก”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 132,
    "zh": "感情",
    "pinyin": "gǎn qíng",
    "thaiPronunciation": "กา̌n ชอี๋ng",
    "th": "ความรู้สึก / ความสัมพันธ์",
    "thToZh": "感情",
    "sentenceZh": "老师让我们学习“感情”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “感情” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 感情 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ความรู้สึก”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 133,
    "zh": "感谢",
    "pinyin": "gǎn xiè",
    "thaiPronunciation": "กา̌n ซอีเอ่อ",
    "th": "ขอบคุณ",
    "thToZh": "感谢",
    "sentenceZh": "老师让我们学习“感谢”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “感谢” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 感谢 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ขอบคุณ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 134,
    "zh": "敢",
    "pinyin": "gǎn",
    "thaiPronunciation": "กา̌n",
    "th": "กล้า",
    "thToZh": "敢",
    "sentenceZh": "老师让我们学习“敢”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “敢” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 敢 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “กล้า”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 135,
    "zh": "赶",
    "pinyin": "gǎn",
    "thaiPronunciation": "กา̌n",
    "th": "รีบ / ตามทัน",
    "thToZh": "赶",
    "sentenceZh": "老师让我们学习“赶”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “赶” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 赶 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “รีบ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 136,
    "zh": "干",
    "pinyin": "gàn",
    "thaiPronunciation": "ก่าn",
    "th": "ทำงาน / ทำ",
    "thToZh": "干",
    "sentenceZh": "老师让我们学习“干”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “干” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 干 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ทำงาน”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 137,
    "zh": "刚",
    "pinyin": "gāng",
    "thaiPronunciation": "กาng",
    "th": "เพิ่ง / พึ่งจะ",
    "thToZh": "刚",
    "sentenceZh": "老师让我们学习“刚”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “刚” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 刚 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “เพิ่ง”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 138,
    "zh": "高速公路",
    "pinyin": "gāo sù gōng lù",
    "thaiPronunciation": "กาโอ สอู้ กโอng ลอู้",
    "th": "ทางด่วน / ทางหลวง",
    "thToZh": "高速公路",
    "sentenceZh": "老师让我们学习“高速公路”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “高速公路” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 高速公路 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ทางด่วน”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 139,
    "zh": "胳膊",
    "pinyin": "gē bo",
    "thaiPronunciation": "กเออ ปโอ",
    "th": "แขน",
    "thToZh": "胳膊",
    "sentenceZh": "老师让我们学习“胳膊”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “胳膊” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 胳膊 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “แขน”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 140,
    "zh": "各",
    "pinyin": "gè",
    "thaiPronunciation": "กเอ่อ",
    "th": "แต่ละ",
    "thToZh": "各",
    "sentenceZh": "老师让我们学习“各”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “各” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 各 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “แต่ละ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 141,
    "zh": "公里",
    "pinyin": "gōng lǐ",
    "thaiPronunciation": "กโอng ลอี",
    "th": "กิโลเมตร",
    "thToZh": "公里",
    "sentenceZh": "老师让我们学习“公里”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “公里” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 公里 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “กิโลเมตร”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 142,
    "zh": "功夫",
    "pinyin": "gōng fu",
    "thaiPronunciation": "กโอng ฝอู",
    "th": "ทักษะ / กังฟู",
    "thToZh": "功夫",
    "sentenceZh": "老师让我们学习“功夫”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “功夫” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 功夫 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ทักษะ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 143,
    "zh": "工资",
    "pinyin": "gōng zī",
    "thaiPronunciation": "กโอng จอี",
    "th": "เงินเดือน",
    "thToZh": "工资",
    "sentenceZh": "老师让我们学习“工资”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “工资” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 工资 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “เงินเดือน”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 144,
    "zh": "共同",
    "pinyin": "gòng tóng",
    "thaiPronunciation": "กโอ้ng ทโอ๋ng",
    "th": "ร่วมกัน",
    "thToZh": "共同",
    "sentenceZh": "老师让我们学习“共同”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “共同” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 共同 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ร่วมกัน”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 145,
    "zh": "够",
    "pinyin": "gòu",
    "thaiPronunciation": "กโอ้อู",
    "th": "พอ",
    "thToZh": "够",
    "sentenceZh": "老师让我们学习“够”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “够” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 够 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “พอ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 146,
    "zh": "购物",
    "pinyin": "gòu wù",
    "thaiPronunciation": "กโอ้อู วอู้",
    "th": "ช้อปปิ้ง",
    "thToZh": "购物",
    "sentenceZh": "老师让我们学习“购物”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “购物” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 购物 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ช้อปปิ้ง”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 147,
    "zh": "估计",
    "pinyin": "gū jì",
    "thaiPronunciation": "กอู จอี้",
    "th": "คาดว่า / ประมาณ",
    "thToZh": "估计",
    "sentenceZh": "老师让我们学习“估计”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “估计” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 估计 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “คาดว่า”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 148,
    "zh": "鼓励",
    "pinyin": "gǔ lì",
    "thaiPronunciation": "กอู ลอี้",
    "th": "ให้กำลังใจ / สนับสนุน",
    "thToZh": "鼓励",
    "sentenceZh": "老师让我们学习“鼓励”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “鼓励” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 鼓励 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ให้กำลังใจ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 149,
    "zh": "故意",
    "pinyin": "gù yì",
    "thaiPronunciation": "กอู้ ยอี้",
    "th": "ตั้งใจ / จงใจ",
    "thToZh": "故意",
    "sentenceZh": "老师让我们学习“故意”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “故意” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 故意 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ตั้งใจ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 150,
    "zh": "顾客",
    "pinyin": "gù kè",
    "thaiPronunciation": "กอู้ คเอ่อ",
    "th": "ลูกค้า",
    "thToZh": "顾客",
    "sentenceZh": "老师让我们学习“顾客”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “顾客” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 顾客 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ลูกค้า”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 151,
    "zh": "挂",
    "pinyin": "guà",
    "thaiPronunciation": "กอู่า",
    "th": "แขวน / วางสาย",
    "thToZh": "挂",
    "sentenceZh": "老师让我们学习“挂”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “挂” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 挂 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “แขวน”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 152,
    "zh": "关键",
    "pinyin": "guān jiàn",
    "thaiPronunciation": "กอูาn จอี่าn",
    "th": "กุญแจสำคัญ",
    "thToZh": "关键",
    "sentenceZh": "老师让我们学习“关键”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “关键” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 关键 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “กุญแจสำคัญ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 153,
    "zh": "观众",
    "pinyin": "guān zhòng",
    "thaiPronunciation": "กอูาn จโอ้ng",
    "th": "ผู้ชม",
    "thToZh": "观众",
    "sentenceZh": "老师让我们学习“观众”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “观众” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 观众 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ผู้ชม”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 154,
    "zh": "管理",
    "pinyin": "guǎn lǐ",
    "thaiPronunciation": "กอูา̌n ลอี",
    "th": "จัดการ / บริหาร",
    "thToZh": "管理",
    "sentenceZh": "老师让我们学习“管理”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “管理” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 管理 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “จัดการ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 155,
    "zh": "光",
    "pinyin": "guāng",
    "thaiPronunciation": "กอูาng",
    "th": "แสง / เพียงแต่",
    "thToZh": "光",
    "sentenceZh": "老师让我们学习“光”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “光” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 光 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “แสง”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 156,
    "zh": "广播",
    "pinyin": "guǎng bō",
    "thaiPronunciation": "กอูา̌ng ปโอ",
    "th": "กระจายเสียง",
    "thToZh": "广播",
    "sentenceZh": "老师让我们学习“广播”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “广播” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 广播 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “กระจายเสียง”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 157,
    "zh": "广告",
    "pinyin": "guǎng gào",
    "thaiPronunciation": "กอูา̌ng ก่าโอ",
    "th": "โฆษณา",
    "thToZh": "广告",
    "sentenceZh": "老师让我们学习“广告”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “广告” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 广告 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “โฆษณา”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 158,
    "zh": "逛",
    "pinyin": "guàng",
    "thaiPronunciation": "กอู่าng",
    "th": "เดินเล่น / เดินเที่ยว",
    "thToZh": "逛",
    "sentenceZh": "老师让我们学习“逛”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “逛” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 逛 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “เดินเล่น”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 159,
    "zh": "规定",
    "pinyin": "guī dìng",
    "thaiPronunciation": "กอูอี ตอี้ng",
    "th": "กำหนด / กฎระเบียบ",
    "thToZh": "规定",
    "sentenceZh": "老师让我们学习“规定”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “规定” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 规定 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “กำหนด”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 160,
    "zh": "国籍",
    "pinyin": "guó jí",
    "thaiPronunciation": "กอูโอ๋ จอี๋",
    "th": "สัญชาติ",
    "thToZh": "国籍",
    "sentenceZh": "老师让我们学习“国籍”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “国籍” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 国籍 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “สัญชาติ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 161,
    "zh": "国际",
    "pinyin": "guó jì",
    "thaiPronunciation": "กอูโอ๋ จอี้",
    "th": "นานาชาติ",
    "thToZh": "国际",
    "sentenceZh": "老师让我们学习“国际”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “国际” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 国际 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “นานาชาติ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 162,
    "zh": "果汁",
    "pinyin": "guǒ zhī",
    "thaiPronunciation": "กอูโอ จอี",
    "th": "น้ำผลไม้",
    "thToZh": "果汁",
    "sentenceZh": "老师让我们学习“果汁”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “果汁” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 果汁 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “น้ำผลไม้”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 163,
    "zh": "过程",
    "pinyin": "guò chéng",
    "thaiPronunciation": "กอูโอ้ ชเอ๋อng",
    "th": "กระบวนการ",
    "thToZh": "过程",
    "sentenceZh": "老师让我们学习“过程”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “过程” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 过程 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “กระบวนการ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 164,
    "zh": "海洋",
    "pinyin": "hǎi yáng",
    "thaiPronunciation": "ฮา̌อี ย๋าng",
    "th": "มหาสมุทร",
    "thToZh": "海洋",
    "sentenceZh": "老师让我们学习“海洋”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “海洋” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 海洋 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “มหาสมุทร”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 165,
    "zh": "害羞",
    "pinyin": "hài xiū",
    "thaiPronunciation": "ฮ่าอี ซอีอู",
    "th": "ขี้อาย",
    "thToZh": "害羞",
    "sentenceZh": "老师让我们学习“害羞”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “害羞” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 害羞 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ขี้อาย”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 166,
    "zh": "寒假",
    "pinyin": "hán jià",
    "thaiPronunciation": "ฮ๋าn จอี่า",
    "th": "ปิดเทอมฤดูหนาว",
    "thToZh": "寒假",
    "sentenceZh": "老师让我们学习“寒假”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “寒假” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 寒假 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ปิดเทอมฤดูหนาว”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 167,
    "zh": "汗",
    "pinyin": "hàn",
    "thaiPronunciation": "ฮ่าn",
    "th": "เหงื่อ",
    "thToZh": "汗",
    "sentenceZh": "老师让我们学习“汗”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “汗” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 汗 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “เหงื่อ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 168,
    "zh": "航班",
    "pinyin": "háng bān",
    "thaiPronunciation": "ฮ๋าng ปาn",
    "th": "เที่ยวบิน",
    "thToZh": "航班",
    "sentenceZh": "老师让我们学习“航班”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “航班” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 航班 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “เที่ยวบิน”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 169,
    "zh": "好处",
    "pinyin": "hǎo chu",
    "thaiPronunciation": "ฮา̌โอ ชอู",
    "th": "ข้อดี / ประโยชน์",
    "thToZh": "好处",
    "sentenceZh": "老师让我们学习“好处”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “好处” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 好处 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ข้อดี”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 170,
    "zh": "好像",
    "pinyin": "hǎo xiàng",
    "thaiPronunciation": "ฮา̌โอ ซอี่าng",
    "th": "เหมือนว่า",
    "thToZh": "好像",
    "sentenceZh": "老师让我们学习“好像”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “好像” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 好像 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “เหมือนว่า”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 171,
    "zh": "号码",
    "pinyin": "hào mǎ",
    "thaiPronunciation": "ฮ่าโอ มา̌",
    "th": "หมายเลข",
    "thToZh": "号码",
    "sentenceZh": "老师让我们学习“号码”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “号码” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 号码 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “หมายเลข”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 172,
    "zh": "合格",
    "pinyin": "hé gé",
    "thaiPronunciation": "ฮเอ๋อ กเอ๋อ",
    "th": "ผ่านมาตรฐาน",
    "thToZh": "合格",
    "sentenceZh": "老师让我们学习“合格”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “合格” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 合格 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ผ่านมาตรฐาน”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 173,
    "zh": "合适",
    "pinyin": "hé shì",
    "thaiPronunciation": "ฮเอ๋อ ซอี้",
    "th": "เหมาะสม",
    "thToZh": "合适",
    "sentenceZh": "老师让我们学习“合适”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “合适” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 合适 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “เหมาะสม”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 174,
    "zh": "盒子",
    "pinyin": "hé zi",
    "thaiPronunciation": "ฮเอ๋อ จอี",
    "th": "กล่อง",
    "thToZh": "盒子",
    "sentenceZh": "老师让我们学习“盒子”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “盒子” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 盒子 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “กล่อง”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 175,
    "zh": "厚",
    "pinyin": "hòu",
    "thaiPronunciation": "ฮโอ้อู",
    "th": "หนา",
    "thToZh": "厚",
    "sentenceZh": "老师让我们学习“厚”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “厚” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 厚 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “หนา”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 176,
    "zh": "后悔",
    "pinyin": "hòu huǐ",
    "thaiPronunciation": "ฮโอ้อู ฮอูอี",
    "th": "เสียใจภายหลัง",
    "thToZh": "后悔",
    "sentenceZh": "老师让我们学习“后悔”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “后悔” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 后悔 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “เสียใจภายหลัง”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 177,
    "zh": "互联网",
    "pinyin": "hù lián wǎng",
    "thaiPronunciation": "ฮอู้ ลอี๋าn วา̌ng",
    "th": "อินเทอร์เน็ต",
    "thToZh": "互联网",
    "sentenceZh": "老师让我们学习“互联网”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “互联网” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 互联网 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “อินเทอร์เน็ต”",
    "image": "🌐",
    "category": "HSK4"
  },
  {
    "id": 178,
    "zh": "互相",
    "pinyin": "hù xiāng",
    "thaiPronunciation": "ฮอู้ ซอีาng",
    "th": "ซึ่งกันและกัน",
    "thToZh": "互相",
    "sentenceZh": "老师让我们学习“互相”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “互相” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 互相 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ซึ่งกันและกัน”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 179,
    "zh": "护士",
    "pinyin": "hù shi",
    "thaiPronunciation": "ฮอู้ ซอี",
    "th": "พยาบาล",
    "thToZh": "护士",
    "sentenceZh": "老师让我们学习“护士”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “护士” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 护士 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “พยาบาล”",
    "image": "🩺",
    "category": "HSK4"
  },
  {
    "id": 180,
    "zh": "怀疑",
    "pinyin": "huái yí",
    "thaiPronunciation": "ฮอู๋าอี ยอี๋",
    "th": "สงสัย",
    "thToZh": "怀疑",
    "sentenceZh": "老师让我们学习“怀疑”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “怀疑” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 怀疑 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “สงสัย”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 181,
    "zh": "回忆",
    "pinyin": "huí yì",
    "thaiPronunciation": "ฮอูอี๋ ยอี้",
    "th": "ความทรงจำ / ระลึกถึง",
    "thToZh": "回忆",
    "sentenceZh": "老师让我们学习“回忆”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “回忆” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 回忆 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ความทรงจำ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 182,
    "zh": "活动",
    "pinyin": "huó dòng",
    "thaiPronunciation": "ฮอูโอ๋ ตโอ้ng",
    "th": "กิจกรรม",
    "thToZh": "活动",
    "sentenceZh": "老师让我们学习“活动”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “活动” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 活动 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “กิจกรรม”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 183,
    "zh": "活泼",
    "pinyin": "huó po",
    "thaiPronunciation": "ฮอูโอ๋ ผโอ",
    "th": "ร่าเริง",
    "thToZh": "活泼",
    "sentenceZh": "老师让我们学习“活泼”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “活泼” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 活泼 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ร่าเริง”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 184,
    "zh": "火",
    "pinyin": "huǒ",
    "thaiPronunciation": "ฮอูโอ",
    "th": "ไฟ",
    "thToZh": "火",
    "sentenceZh": "老师让我们学习“火”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “火” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 火 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ไฟ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 185,
    "zh": "获得",
    "pinyin": "huò dé",
    "thaiPronunciation": "ฮอูโอ้ ตเอ๋อ",
    "th": "ได้รับ",
    "thToZh": "获得",
    "sentenceZh": "老师让我们学习“获得”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “获得” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 获得 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ได้รับ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 186,
    "zh": "基础",
    "pinyin": "jī chǔ",
    "thaiPronunciation": "จอี ชอู",
    "th": "พื้นฐาน",
    "thToZh": "基础",
    "sentenceZh": "老师让我们学习“基础”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “基础” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 基础 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “พื้นฐาน”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 187,
    "zh": "激动",
    "pinyin": "jī dòng",
    "thaiPronunciation": "จอี ตโอ้ng",
    "th": "ตื่นเต้น / กระตุ้น",
    "thToZh": "激动",
    "sentenceZh": "老师让我们学习“激动”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “激动” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 激动 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ตื่นเต้น”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 188,
    "zh": "积极",
    "pinyin": "jī jí",
    "thaiPronunciation": "จอี จอี๋",
    "th": "กระตือรือร้น / เชิงบวก",
    "thToZh": "积极",
    "sentenceZh": "老师让我们学习“积极”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “积极” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 积极 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “กระตือรือร้น”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 189,
    "zh": "积累",
    "pinyin": "jī lěi",
    "thaiPronunciation": "จอี ลเอออี",
    "th": "สะสม",
    "thToZh": "积累",
    "sentenceZh": "老师让我们学习“积累”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “积累” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 积累 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “สะสม”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 190,
    "zh": "即使",
    "pinyin": "jí shǐ",
    "thaiPronunciation": "จอี๋ ซอี",
    "th": "แม้ว่า",
    "thToZh": "即使",
    "sentenceZh": "老师让我们学习“即使”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “即使” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 即使 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “แม้ว่า”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 191,
    "zh": "及时",
    "pinyin": "jí shí",
    "thaiPronunciation": "จอี๋ ซอี๋",
    "th": "ทันเวลา",
    "thToZh": "及时",
    "sentenceZh": "老师让我们学习“及时”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “及时” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 及时 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ทันเวลา”",
    "image": "⏰",
    "category": "HSK4"
  },
  {
    "id": 192,
    "zh": "寄",
    "pinyin": "jì",
    "thaiPronunciation": "จอี้",
    "th": "ส่งไปรษณีย์",
    "thToZh": "寄",
    "sentenceZh": "老师让我们学习“寄”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “寄” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 寄 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ส่งไปรษณีย์”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 193,
    "zh": "技术",
    "pinyin": "jì shù",
    "thaiPronunciation": "จอี้ ซอู้",
    "th": "เทคโนโลยี / ทักษะ",
    "thToZh": "技术",
    "sentenceZh": "老师让我们学习“技术”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “技术” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 技术 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “เทคโนโลยี”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 194,
    "zh": "既然",
    "pinyin": "jì rán",
    "thaiPronunciation": "จอี้ ร๋าn",
    "th": "ในเมื่อ",
    "thToZh": "既然",
    "sentenceZh": "老师让我们学习“既然”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “既然” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 既然 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ในเมื่อ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 195,
    "zh": "继续",
    "pinyin": "jì xù",
    "thaiPronunciation": "จอี้ ซอู้",
    "th": "ต่อเนื่อง / ดำเนินต่อ",
    "thToZh": "继续",
    "sentenceZh": "老师让我们学习“继续”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “继续” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 继续 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ต่อเนื่อง”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 196,
    "zh": "计划",
    "pinyin": "jì huà",
    "thaiPronunciation": "จอี้ ฮอู่า",
    "th": "แผน / วางแผน",
    "thToZh": "计划",
    "sentenceZh": "老师让我们学习“计划”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “计划” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 计划 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “แผน”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 197,
    "zh": "记者",
    "pinyin": "jì zhě",
    "thaiPronunciation": "จอี้ จเออ",
    "th": "นักข่าว",
    "thToZh": "记者",
    "sentenceZh": "老师让我们学习“记者”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “记者” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 记者 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “นักข่าว”",
    "image": "📰",
    "category": "HSK4"
  },
  {
    "id": 198,
    "zh": "加班",
    "pinyin": "jiā bān",
    "thaiPronunciation": "จอีา ปาn",
    "th": "ทำงานล่วงเวลา",
    "thToZh": "加班",
    "sentenceZh": "老师让我们学习“加班”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “加班” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 加班 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ทำงานล่วงเวลา”",
    "image": "⏰",
    "category": "HSK4"
  },
  {
    "id": 199,
    "zh": "加油站",
    "pinyin": "jiā yóu zhàn",
    "thaiPronunciation": "จอีา ยโอ๋อู จ่าn",
    "th": "ปั๊มน้ำมัน",
    "thToZh": "加油站",
    "sentenceZh": "老师让我们学习“加油站”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “加油站” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 加油站 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ปั๊มน้ำมัน”",
    "image": "⛽",
    "category": "HSK4"
  },
  {
    "id": 200,
    "zh": "家具",
    "pinyin": "jiā jù",
    "thaiPronunciation": "จอีา จอู้",
    "th": "เฟอร์นิเจอร์",
    "thToZh": "家具",
    "sentenceZh": "老师让我们学习“家具”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “家具” zhè ge cí",
    "sentenceThaiPronunciation": "ลา̌โอ ซอี ร่าng วโอ มเอิน ซอูเอ๋อ ซอี๋ 家具 จเอ่อ กเออ ชอี๋",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “เฟอร์นิเจอร์”",
    "image": "🀄",
    "category": "HSK4"
  }
];
