export type Flashcard = {
  id:  number;
   "zh":  string;
   "pinyin":  string;
   "thaiPronunciation":  string;
   "th":  string;
   "thToZh":  string;
   "sentenceZh":  string;
   "sentencePinyin":  string;
   "sentenceThaiPronunciation":  string;
   "sentenceTh":  string;
   "image":  string;
   "category":  "HSK4"};

export const hsk4Data: Flashcard[] = [
  {
    "id": 1,
    "zh": "爱情",
    "pinyin": "ài qíng",
    "thaiPronunciation": "khwam rak",
    "th": "ความรัก",
    "thToZh": "爱情",
    "sentenceZh": "老师让我们学习“爱情”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “爱情” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า khwam rak",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ความรัก”",
    "image": "❤️",
    "category": "HSK4"
  },
  {
    "id": 2,
    "zh": "安排",
    "pinyin": "ān pái",
    "thaiPronunciation": "chatkan wang phaen",
    "th": "จัดการ / วางแผน",
    "thToZh": "安排",
    "sentenceZh": "老师让我们学习“安排”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “安排” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า chatkan",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “จัดการ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 3,
    "zh": "安全",
    "pinyin": "ān quán",
    "thaiPronunciation": "plodphai khwam plodphai",
    "th": "ปลอดภัย / ความปลอดภัย",
    "thToZh": "安全",
    "sentenceZh": "老师让我们学习“安全”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “安全” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า plodphai",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ปลอดภัย”",
    "image": "🛡️",
    "category": "HSK4"
  },
  {
    "id": 4,
    "zh": "按时",
    "pinyin": "àn shí",
    "thaiPronunciation": "trong wela",
    "th": "ตรงเวลา",
    "thToZh": "按时",
    "sentenceZh": "老师让我们学习“按时”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “按时” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า trong wela",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ตรงเวลา”",
    "image": "⏰",
    "category": "HSK4"
  },
  {
    "id": 5,
    "zh": "按照",
    "pinyin": "àn zhào",
    "thaiPronunciation": "tam tam thi",
    "th": "ตาม / ตามที่",
    "thToZh": "按照",
    "sentenceZh": "老师让我们学习“按照”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “按照” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า tam",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ตาม”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 6,
    "zh": "百分之",
    "pinyin": "bǎi fēn zhī",
    "thaiPronunciation": "เปอร์เซ็นต์",
    "th": "เปอร์เซ็นต์",
    "thToZh": "百分之",
    "sentenceZh": "老师让我们学习“百分之”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “百分之” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า เปอร์เซ็นต์",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “เปอร์เซ็นต์”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 7,
    "zh": "棒",
    "pinyin": "bàng",
    "thaiPronunciation": "yiam keng",
    "th": "เยี่ยม / เก่ง",
    "thToZh": "棒",
    "sentenceZh": "老师让我们学习“棒”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “棒” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า yiam",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “เยี่ยม”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 8,
    "zh": "包子",
    "pinyin": "bāo zi",
    "thaiPronunciation": "salapao",
    "th": "ซาลาเปา",
    "thToZh": "包子",
    "sentenceZh": "老师让我们学习“包子”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “包子” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า salapao",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ซาลาเปา”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 9,
    "zh": "保护",
    "pinyin": "bǎo hù",
    "thaiPronunciation": "pokpong khumkhrong",
    "th": "ปกป้อง / คุ้มครอง",
    "thToZh": "保护",
    "sentenceZh": "老师让我们学习“保护”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “保护” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า pokpong",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ปกป้อง”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 10,
    "zh": "保证",
    "pinyin": "bǎo zhèng",
    "thaiPronunciation": "rap prakan",
    "th": "รับประกัน",
    "thToZh": "保证",
    "sentenceZh": "老师让我们学习“保证”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “保证” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า rap prakan",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “รับประกัน”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 11,
    "zh": "报名",
    "pinyin": "bào míng",
    "thaiPronunciation": "samak long thabian",
    "th": "สมัคร / ลงทะเบียน",
    "thToZh": "报名",
    "sentenceZh": "老师让我们学习“报名”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “报名” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า samak",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “สมัคร”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 12,
    "zh": "抱",
    "pinyin": "bào",
    "thaiPronunciation": "kot um",
    "th": "กอด / อุ้ม",
    "thToZh": "抱",
    "sentenceZh": "老师让我们学习“抱”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “抱” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า kot",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “กอด”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 13,
    "zh": "抱歉",
    "pinyin": "bào qiàn",
    "thaiPronunciation": "kho thot",
    "th": "ขอโทษ",
    "thToZh": "抱歉",
    "sentenceZh": "老师让我们学习“抱歉”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “抱歉” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า kho thot",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ขอโทษ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 14,
    "zh": "倍",
    "pinyin": "bèi",
    "thaiPronunciation": "thao thao tua",
    "th": "เท่า / เท่าตัว",
    "thToZh": "倍",
    "sentenceZh": "老师让我们学习“倍”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “倍” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า thao",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “เท่า”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 15,
    "zh": "本来",
    "pinyin": "běn lái",
    "thaiPronunciation": "doem thi แต่แรก",
    "th": "เดิมที / แต่แรก",
    "thToZh": "本来",
    "sentenceZh": "老师让我们学习“本来”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “本来” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า doem thi",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “เดิมที”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 16,
    "zh": "笨",
    "pinyin": "bèn",
    "thaiPronunciation": "ngo thuem",
    "th": "โง่ / ทึ่ม",
    "thToZh": "笨",
    "sentenceZh": "老师让我们学习“笨”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “笨” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า ngo",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “โง่”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 17,
    "zh": "比如",
    "pinyin": "bǐ rú",
    "thaiPronunciation": "chen tua yang chen",
    "th": "เช่น / ตัวอย่างเช่น",
    "thToZh": "比如",
    "sentenceZh": "老师让我们学习“比如”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “比如” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า chen",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “เช่น”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 18,
    "zh": "毕业",
    "pinyin": "bì yè",
    "thaiPronunciation": "rian chop",
    "th": "เรียนจบ",
    "thToZh": "毕业",
    "sentenceZh": "老师让我们学习“毕业”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “毕业” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า rian chop",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “เรียนจบ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 19,
    "zh": "遍",
    "pinyin": "biàn",
    "thaiPronunciation": "rop khrang",
    "th": "รอบ / ครั้ง",
    "thToZh": "遍",
    "sentenceZh": "老师让我们学习“遍”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “遍” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า rop",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “รอบ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 20,
    "zh": "标准",
    "pinyin": "biāo zhǔn",
    "thaiPronunciation": "mattrathan",
    "th": "มาตรฐาน",
    "thToZh": "标准",
    "sentenceZh": "老师让我们学习“标准”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “标准” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า mattrathan",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “มาตรฐาน”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 21,
    "zh": "表格",
    "pinyin": "biǎo gé",
    "thaiPronunciation": "baep form tarang",
    "th": "แบบฟอร์ม / ตาราง",
    "thToZh": "表格",
    "sentenceZh": "老师让我们学习“表格”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “表格” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า baep form",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “แบบฟอร์ม”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 22,
    "zh": "表示",
    "pinyin": "biǎo shì",
    "thaiPronunciation": "sa-daeng บอก",
    "th": "แสดง / บอก",
    "thToZh": "表示",
    "sentenceZh": "老师让我们学习“表示”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “表示” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า sa-daeng",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “แสดง”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 23,
    "zh": "表演",
    "pinyin": "biǎo yǎn",
    "thaiPronunciation": "sa-daeng",
    "th": "แสดง",
    "thToZh": "表演",
    "sentenceZh": "老师让我们学习“表演”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “表演” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า sa-daeng",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “แสดง”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 24,
    "zh": "表扬",
    "pinyin": "biǎo yáng",
    "thaiPronunciation": "chomchoei",
    "th": "ชมเชย",
    "thToZh": "表扬",
    "sentenceZh": "老师让我们学习“表扬”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “表扬” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า chomchoei",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ชมเชย”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 25,
    "zh": "饼干",
    "pinyin": "bǐng gān",
    "thaiPronunciation": "biskit khukki",
    "th": "บิสกิต / คุกกี้",
    "thToZh": "饼干",
    "sentenceZh": "老师让我们学习“饼干”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “饼干” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า biskit",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “บิสกิต”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 26,
    "zh": "并且",
    "pinyin": "bìng qiě",
    "thaiPronunciation": "lae ik thang",
    "th": "และ / อีกทั้ง",
    "thToZh": "并且",
    "sentenceZh": "老师让我们学习“并且”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “并且” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า lae",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “และ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 27,
    "zh": "博士",
    "pinyin": "bó shì",
    "thaiPronunciation": "parinya ek ดอกเตอร์",
    "th": "ปริญญาเอก / ดอกเตอร์",
    "thToZh": "博士",
    "sentenceZh": "老师让我们学习“博士”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “博士” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า parinya ek",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ปริญญาเอก”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 28,
    "zh": "不过",
    "pinyin": "bú guò",
    "thaiPronunciation": "tae wa yangrai ko tam",
    "th": "แต่ว่า / อย่างไรก็ตาม",
    "thToZh": "不过",
    "sentenceZh": "老师让我们学习“不过”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “不过” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า tae wa",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “แต่ว่า”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 29,
    "zh": "不得不",
    "pinyin": "bù dé bù",
    "thaiPronunciation": "champen tong",
    "th": "จำเป็นต้อง",
    "thToZh": "不得不",
    "sentenceZh": "老师让我们学习“不得不”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “不得不” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า champen tong",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “จำเป็นต้อง”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 30,
    "zh": "不管",
    "pinyin": "bù guǎn",
    "thaiPronunciation": "mai wa",
    "th": "ไม่ว่า",
    "thToZh": "不管",
    "sentenceZh": "老师让我们学习“不管”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “不管” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า mai wa",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ไม่ว่า”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 31,
    "zh": "不仅",
    "pinyin": "bù jǐn",
    "thaiPronunciation": "mai phiang tae",
    "th": "ไม่เพียงแต่",
    "thToZh": "不仅",
    "sentenceZh": "老师让我们学习“不仅”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “不仅” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า mai phiang tae",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ไม่เพียงแต่”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 32,
    "zh": "部分",
    "pinyin": "bù fen",
    "thaiPronunciation": "suan nueng bang suan",
    "th": "ส่วนหนึ่ง / บางส่วน",
    "thToZh": "部分",
    "sentenceZh": "老师让我们学习“部分”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “部分” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า suan nueng",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ส่วนหนึ่ง”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 33,
    "zh": "擦",
    "pinyin": "cā",
    "thaiPronunciation": "chet",
    "th": "เช็ด",
    "thToZh": "擦",
    "sentenceZh": "老师让我们学习“擦”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “擦” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า chet",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “เช็ด”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 34,
    "zh": "猜",
    "pinyin": "cāi",
    "thaiPronunciation": "dao",
    "th": "เดา",
    "thToZh": "猜",
    "sentenceZh": "老师让我们学习“猜”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “猜” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า dao",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “เดา”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 35,
    "zh": "材料",
    "pinyin": "cái liào",
    "thaiPronunciation": "watsadu khomun",
    "th": "วัสดุ / ข้อมูล",
    "thToZh": "材料",
    "sentenceZh": "老师让我们学习“材料”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “材料” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า watsadu",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “วัสดุ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 36,
    "zh": "参观",
    "pinyin": "cān guān",
    "thaiPronunciation": "yiam chom",
    "th": "เยี่ยมชม",
    "thToZh": "参观",
    "sentenceZh": "老师让我们学习“参观”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “参观” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า yiam chom",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “เยี่ยมชม”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 37,
    "zh": "餐厅",
    "pinyin": "cān tīng",
    "thaiPronunciation": "ran ahan",
    "th": "ร้านอาหาร",
    "thToZh": "餐厅",
    "sentenceZh": "老师让我们学习“餐厅”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “餐厅” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า ran ahan",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ร้านอาหาร”",
    "image": "🍽️",
    "category": "HSK4"
  },
  {
    "id": 38,
    "zh": "厕所",
    "pinyin": "cè suǒ",
    "thaiPronunciation": "hong nam",
    "th": "ห้องน้ำ",
    "thToZh": "厕所",
    "sentenceZh": "老师让我们学习“厕所”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “厕所” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า hong nam",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ห้องน้ำ”",
    "image": "🚻",
    "category": "HSK4"
  },
  {
    "id": 39,
    "zh": "差不多",
    "pinyin": "chà bu duō",
    "thaiPronunciation": "kueap พอๆ กัน",
    "th": "เกือบ / พอๆ กัน",
    "thToZh": "差不多",
    "sentenceZh": "老师让我们学习“差不多”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “差不多” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า kueap",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “เกือบ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 40,
    "zh": "尝",
    "pinyin": "cháng",
    "thaiPronunciation": "long chim ลอง",
    "th": "ลองชิม / ลอง",
    "thToZh": "尝",
    "sentenceZh": "老师让我们学习“尝”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “尝” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า long chim",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ลองชิม”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 41,
    "zh": "长城",
    "pinyin": "cháng chéng",
    "thaiPronunciation": "kamphaeng mueang chin",
    "th": "กำแพงเมืองจีน",
    "thToZh": "长城",
    "sentenceZh": "老师让我们学习“长城”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “长城” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า kamphaeng mueang chin",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “กำแพงเมืองจีน”",
    "image": "🧱",
    "category": "HSK4"
  },
  {
    "id": 42,
    "zh": "长江",
    "pinyin": "cháng jiāng",
    "thaiPronunciation": "mae nam yaengsi",
    "th": "แม่น้ำแยงซี",
    "thToZh": "长江",
    "sentenceZh": "老师让我们学习“长江”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “长江” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า mae nam yaengsi",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “แม่น้ำแยงซี”",
    "image": "🌊",
    "category": "HSK4"
  },
  {
    "id": 43,
    "zh": "场",
    "pinyin": "chǎng",
    "thaiPronunciation": "sanam งาน rop",
    "th": "สนาม / งาน / รอบ",
    "thToZh": "场",
    "sentenceZh": "老师让我们学习“场”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “场” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า sanam",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “สนาม”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 44,
    "zh": "超过",
    "pinyin": "chāo guò",
    "thaiPronunciation": "koen เกินกว่า",
    "th": "เกิน / เกินกว่า",
    "thToZh": "超过",
    "sentenceZh": "老师让我们学习“超过”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “超过” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า koen",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “เกิน”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 45,
    "zh": "乘坐",
    "pinyin": "chéng zuò",
    "thaiPronunciation": "nang โดยสาร",
    "th": "นั่ง / โดยสาร",
    "thToZh": "乘坐",
    "sentenceZh": "老师让我们学习“乘坐”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “乘坐” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า nang",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “นั่ง”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 46,
    "zh": "成功",
    "pinyin": "chéng gōng",
    "thaiPronunciation": "samret",
    "th": "สำเร็จ",
    "thToZh": "成功",
    "sentenceZh": "老师让我们学习“成功”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “成功” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า samret",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “สำเร็จ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 47,
    "zh": "成为",
    "pinyin": "chéng wéi",
    "thaiPronunciation": "klai pen",
    "th": "กลายเป็น",
    "thToZh": "成为",
    "sentenceZh": "老师让我们学习“成为”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “成为” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า klai pen",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “กลายเป็น”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 48,
    "zh": "诚实",
    "pinyin": "chéng shí",
    "thaiPronunciation": "suesat",
    "th": "ซื่อสัตย์",
    "thToZh": "诚实",
    "sentenceZh": "老师让我们学习“诚实”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “诚实” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า suesat",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ซื่อสัตย์”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 49,
    "zh": "吃惊",
    "pinyin": "chī jīng",
    "thaiPronunciation": "tokchai",
    "th": "ตกใจ",
    "thToZh": "吃惊",
    "sentenceZh": "老师让我们学习“吃惊”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “吃惊” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า tokchai",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ตกใจ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 50,
    "zh": "重新",
    "pinyin": "chóng xīn",
    "thaiPronunciation": "ik khrang ใหม่อีกครั้ง",
    "th": "อีกครั้ง / ใหม่อีกครั้ง",
    "thToZh": "重新",
    "sentenceZh": "老师让我们学习“重新”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “重新” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า ik khrang",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “อีกครั้ง”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 51,
    "zh": "抽烟",
    "pinyin": "chōu yān",
    "thaiPronunciation": "sup buri",
    "th": "สูบบุหรี่",
    "thToZh": "抽烟",
    "sentenceZh": "老师让我们学习“抽烟”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “抽烟” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า sup buri",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “สูบบุหรี่”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 52,
    "zh": "出差",
    "pinyin": "chū chāi",
    "thaiPronunciation": "เดินทางไปทำงานต่างที่",
    "th": "เดินทางไปทำงานต่างที่",
    "thToZh": "出差",
    "sentenceZh": "老师让我们学习“出差”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “出差” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า เดินทางไปทำงานต่างที่",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “เดินทางไปทำงานต่างที่”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 53,
    "zh": "出发",
    "pinyin": "chū fā",
    "thaiPronunciation": "ok doenthang",
    "th": "ออกเดินทาง",
    "thToZh": "出发",
    "sentenceZh": "老师让我们学习“出发”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “出发” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า ok doenthang",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ออกเดินทาง”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 54,
    "zh": "出生",
    "pinyin": "chū shēng",
    "thaiPronunciation": "koet",
    "th": "เกิด",
    "thToZh": "出生",
    "sentenceZh": "老师让我们学习“出生”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “出生” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า koet",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “เกิด”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 55,
    "zh": "出现",
    "pinyin": "chū xiàn",
    "thaiPronunciation": "prakot koet khuen",
    "th": "ปรากฏ / เกิดขึ้น",
    "thToZh": "出现",
    "sentenceZh": "老师让我们学习“出现”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “出现” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า prakot",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ปรากฏ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 56,
    "zh": "厨房",
    "pinyin": "chú fáng",
    "thaiPronunciation": "hong khrua",
    "th": "ห้องครัว",
    "thToZh": "厨房",
    "sentenceZh": "老师让我们学习“厨房”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “厨房” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า hong khrua",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ห้องครัว”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 57,
    "zh": "传真",
    "pinyin": "chuán zhēn",
    "thaiPronunciation": "faek",
    "th": "แฟกซ์",
    "thToZh": "传真",
    "sentenceZh": "老师让我们学习“传真”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “传真” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า faek",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “แฟกซ์”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 58,
    "zh": "窗户",
    "pinyin": "chuāng hu",
    "thaiPronunciation": "na tang",
    "th": "หน้าต่าง",
    "thToZh": "窗户",
    "sentenceZh": "老师让我们学习“窗户”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “窗户” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า na tang",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “หน้าต่าง”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 59,
    "zh": "词语",
    "pinyin": "cí yǔ",
    "thaiPronunciation": "kham sap วลี",
    "th": "คำศัพท์ / วลี",
    "thToZh": "词语",
    "sentenceZh": "老师让我们学习“词语”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “词语” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า kham sap",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “คำศัพท์”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 60,
    "zh": "从来",
    "pinyin": "cóng lái",
    "thaiPronunciation": "samoe ma ไม่เคย ในประโยคปฏิเสธ",
    "th": "เสมอมา / ไม่เคย(ในประโยคปฏิเสธ)",
    "thToZh": "从来",
    "sentenceZh": "老师让我们学习“从来”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “从来” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า samoe ma",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “เสมอมา”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 61,
    "zh": "粗心",
    "pinyin": "cū xīn",
    "thaiPronunciation": "saphrao",
    "th": "สะเพร่า",
    "thToZh": "粗心",
    "sentenceZh": "老师让我们学习“粗心”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “粗心” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า saphrao",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “สะเพร่า”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 62,
    "zh": "存",
    "pinyin": "cún",
    "thaiPronunciation": "kep ฝาก มีอยู่",
    "th": "เก็บ / ฝาก / มีอยู่",
    "thToZh": "存",
    "sentenceZh": "老师让我们学习“存”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “存” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า kep",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “เก็บ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 63,
    "zh": "错误",
    "pinyin": "cuò wù",
    "thaiPronunciation": "kho phitphlat",
    "th": "ข้อผิดพลาด",
    "thToZh": "错误",
    "sentenceZh": "老师让我们学习“错误”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “错误” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า kho phitphlat",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ข้อผิดพลาด”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 64,
    "zh": "答案",
    "pinyin": "dá àn",
    "thaiPronunciation": "kham top",
    "th": "คำตอบ",
    "thToZh": "答案",
    "sentenceZh": "老师让我们学习“答案”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “答案” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า kham top",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “คำตอบ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 65,
    "zh": "打扮",
    "pinyin": "dǎ ban",
    "thaiPronunciation": "taeng tua",
    "th": "แต่งตัว",
    "thToZh": "打扮",
    "sentenceZh": "老师让我们学习“打扮”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “打扮” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า taeng tua",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “แต่งตัว”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 66,
    "zh": "打扰",
    "pinyin": "dǎ rǎo",
    "thaiPronunciation": "ropkuan",
    "th": "รบกวน",
    "thToZh": "打扰",
    "sentenceZh": "老师让我们学习“打扰”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “打扰” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า ropkuan",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “รบกวน”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 67,
    "zh": "打印",
    "pinyin": "dǎ yìn",
    "thaiPronunciation": "phim",
    "th": "พิมพ์",
    "thToZh": "打印",
    "sentenceZh": "老师让我们学习“打印”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “打印” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า phim",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “พิมพ์”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 68,
    "zh": "打招呼",
    "pinyin": "dǎ zhāo hu",
    "thaiPronunciation": "thakthai",
    "th": "ทักทาย",
    "thToZh": "打招呼",
    "sentenceZh": "老师让我们学习“打招呼”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “打招呼” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า thakthai",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ทักทาย”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 69,
    "zh": "打折",
    "pinyin": "dǎ zhé",
    "thaiPronunciation": "lot rakha",
    "th": "ลดราคา",
    "thToZh": "打折",
    "sentenceZh": "老师让我们学习“打折”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “打折” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า lot rakha",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ลดราคา”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 70,
    "zh": "打针",
    "pinyin": "dǎ zhēn",
    "thaiPronunciation": "chit ya",
    "th": "ฉีดยา",
    "thToZh": "打针",
    "sentenceZh": "老师让我们学习“打针”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “打针” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า chit ya",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ฉีดยา”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 71,
    "zh": "大概",
    "pinyin": "dà gài",
    "thaiPronunciation": "praman น่าจะ",
    "th": "ประมาณ / น่าจะ",
    "thToZh": "大概",
    "sentenceZh": "老师让我们学习“大概”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “大概” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า praman",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ประมาณ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 72,
    "zh": "大使馆",
    "pinyin": "dà shǐ guǎn",
    "thaiPronunciation": "sathanthut",
    "th": "สถานทูต",
    "thToZh": "大使馆",
    "sentenceZh": "老师让我们学习“大使馆”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “大使馆” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า sathanthut",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “สถานทูต”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 73,
    "zh": "大约",
    "pinyin": "dà yuē",
    "thaiPronunciation": "praman",
    "th": "ประมาณ",
    "thToZh": "大约",
    "sentenceZh": "老师让我们学习“大约”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “大约” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า praman",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ประมาณ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 74,
    "zh": "大夫",
    "pinyin": "dài fu",
    "thaiPronunciation": "mo",
    "th": "หมอ",
    "thToZh": "大夫",
    "sentenceZh": "老师让我们学习“大夫”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “大夫” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า mo",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “หมอ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 75,
    "zh": "戴",
    "pinyin": "dài",
    "thaiPronunciation": "suam ใส่",
    "th": "สวม / ใส่",
    "thToZh": "戴",
    "sentenceZh": "老师让我们学习“戴”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “戴” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า suam",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “สวม”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 76,
    "zh": "当",
    "pinyin": "dāng",
    "thaiPronunciation": "pen ตอนที่",
    "th": "เป็น / ตอนที่",
    "thToZh": "当",
    "sentenceZh": "老师让我们学习“当”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “当” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า pen",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “เป็น”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 77,
    "zh": "当时",
    "pinyin": "dāng shí",
    "thaiPronunciation": "ton nan",
    "th": "ตอนนั้น",
    "thToZh": "当时",
    "sentenceZh": "老师让我们学习“当时”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “当时” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า ton nan",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ตอนนั้น”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 78,
    "zh": "刀",
    "pinyin": "dāo",
    "thaiPronunciation": "mit",
    "th": "มีด",
    "thToZh": "刀",
    "sentenceZh": "老师让我们学习“刀”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “刀” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า mit",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “มีด”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 79,
    "zh": "导游",
    "pinyin": "dǎo yóu",
    "thaiPronunciation": "gaet มัคคุเทศก์",
    "th": "ไกด์ / มัคคุเทศก์",
    "thToZh": "导游",
    "sentenceZh": "老师让我们学习“导游”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “导游” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า gaet",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ไกด์”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 80,
    "zh": "倒",
    "pinyin": "dào",
    "thaiPronunciation": "klap dan เทกลับ",
    "th": "กลับด้าน / เทกลับ",
    "thToZh": "倒",
    "sentenceZh": "老师让我们学习“倒”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “倒” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า klap dan",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “กลับด้าน”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 81,
    "zh": "到处",
    "pinyin": "dào chù",
    "thaiPronunciation": "thuk thi",
    "th": "ทุกที่",
    "thToZh": "到处",
    "sentenceZh": "老师让我们学习“到处”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “到处” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า thuk thi",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ทุกที่”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 82,
    "zh": "到底",
    "pinyin": "dào dǐ",
    "thaiPronunciation": "thai thi sut ตกลงว่า",
    "th": "ท้ายที่สุด / ตกลงว่า",
    "thToZh": "到底",
    "sentenceZh": "老师让我们学习“到底”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “到底” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า thai thi sut",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ท้ายที่สุด”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 83,
    "zh": "道歉",
    "pinyin": "dào qiàn",
    "thaiPronunciation": "kho thot",
    "th": "ขอโทษ",
    "thToZh": "道歉",
    "sentenceZh": "老师让我们学习“道歉”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “道歉” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า kho thot",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ขอโทษ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 84,
    "zh": "得",
    "pinyin": "dé",
    "thaiPronunciation": "tong ได้",
    "th": "ต้อง / ได้",
    "thToZh": "得",
    "sentenceZh": "老师让我们学习“得”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “得” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า tong",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ต้อง”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 85,
    "zh": "得意",
    "pinyin": "dé yì",
    "thaiPronunciation": "phumchai ได้ใจ",
    "th": "ภูมิใจ / ได้ใจ",
    "thToZh": "得意",
    "sentenceZh": "老师让我们学习“得意”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “得意” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า phumchai",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ภูมิใจ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 86,
    "zh": "登机牌",
    "pinyin": "dēng jī pái",
    "thaiPronunciation": "boarding pass",
    "th": "บอร์ดดิ้งพาส",
    "thToZh": "登机牌",
    "sentenceZh": "老师让我们学习“登机牌”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “登机牌” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า boarding pass",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “บอร์ดดิ้งพาส”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 87,
    "zh": "等",
    "pinyin": "děng",
    "thaiPronunciation": "ฯลฯ รอ",
    "th": "ฯลฯ / รอ",
    "thToZh": "等",
    "sentenceZh": "老师让我们学习“等”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “等” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า ฯลฯ",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ฯลฯ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 88,
    "zh": "低",
    "pinyin": "dī",
    "thaiPronunciation": "tam",
    "th": "ต่ำ",
    "thToZh": "低",
    "sentenceZh": "老师让我们学习“低”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “低” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า tam",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ต่ำ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 89,
    "zh": "底",
    "pinyin": "dǐ",
    "thaiPronunciation": "dan lang ก้น",
    "th": "ด้านล่าง / ก้น",
    "thToZh": "底",
    "sentenceZh": "老师让我们学习“底”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “底” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า dan lang",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ด้านล่าง”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 90,
    "zh": "地点",
    "pinyin": "dì diǎn",
    "thaiPronunciation": "sathan thi",
    "th": "สถานที่",
    "thToZh": "地点",
    "sentenceZh": "老师让我们学习“地点”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “地点” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า sathan thi",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “สถานที่”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 91,
    "zh": "地球",
    "pinyin": "dì qiú",
    "thaiPronunciation": "lok",
    "th": "โลก",
    "thToZh": "地球",
    "sentenceZh": "老师让我们学习“地球”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “地球” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า lok",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “โลก”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 92,
    "zh": "地址",
    "pinyin": "dì zhǐ",
    "thaiPronunciation": "thi yu",
    "th": "ที่อยู่",
    "thToZh": "地址",
    "sentenceZh": "老师让我们学习“地址”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “地址” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า thi yu",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ที่อยู่”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 93,
    "zh": "掉",
    "pinyin": "diào",
    "thaiPronunciation": "tok หล่น หาย",
    "th": "ตก / หล่น / หาย",
    "thToZh": "掉",
    "sentenceZh": "老师让我们学习“掉”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “掉” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า tok",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ตก”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 94,
    "zh": "调查",
    "pinyin": "diào chá",
    "thaiPronunciation": "samruat ตรวจสอบ",
    "th": "สำรวจ / ตรวจสอบ",
    "thToZh": "调查",
    "sentenceZh": "老师让我们学习“调查”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “调查” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า samruat",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “สำรวจ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 95,
    "zh": "丢",
    "pinyin": "diū",
    "thaiPronunciation": "tham hai ทิ้ง",
    "th": "ทำหาย / ทิ้ง",
    "thToZh": "丢",
    "sentenceZh": "老师让我们学习“丢”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “丢” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า tham hai",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ทำหาย”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 96,
    "zh": "动作",
    "pinyin": "dòng zuò",
    "thaiPronunciation": "kan khlueanwai ท่าทาง",
    "th": "การเคลื่อนไหว / ท่าทาง",
    "thToZh": "动作",
    "sentenceZh": "老师让我们学习“动作”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “动作” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า kan khlueanwai",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “การเคลื่อนไหว”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 97,
    "zh": "堵车",
    "pinyin": "dǔ chē",
    "thaiPronunciation": "rot tit",
    "th": "รถติด",
    "thToZh": "堵车",
    "sentenceZh": "老师让我们学习“堵车”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “堵车” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า rot tit",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “รถติด”",
    "image": "🚗",
    "category": "HSK4"
  },
  {
    "id": 98,
    "zh": "肚子",
    "pinyin": "dù zi",
    "thaiPronunciation": "thong",
    "th": "ท้อง",
    "thToZh": "肚子",
    "sentenceZh": "老师让我们学习“肚子”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “肚子” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า thong",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ท้อง”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 99,
    "zh": "短信",
    "pinyin": "duǎn xìn",
    "thaiPronunciation": "khokhwam san SMS",
    "th": "ข้อความสั้น / SMS",
    "thToZh": "短信",
    "sentenceZh": "老师让我们学习“短信”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “短信” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า khokhwam san",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ข้อความสั้น”",
    "image": "💬",
    "category": "HSK4"
  },
  {
    "id": 100,
    "zh": "对话",
    "pinyin": "duì huà",
    "thaiPronunciation": "bot sonthana",
    "th": "บทสนทนา",
    "thToZh": "对话",
    "sentenceZh": "老师让我们学习“对话”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “对话” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า bot sonthana",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “บทสนทนา”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 101,
    "zh": "对面",
    "pinyin": "duì miàn",
    "thaiPronunciation": "trong kham",
    "th": "ตรงข้าม",
    "thToZh": "对面",
    "sentenceZh": "老师让我们学习“对面”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “对面” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า trong kham",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ตรงข้าม”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 102,
    "zh": "对于",
    "pinyin": "duì yú",
    "thaiPronunciation": "samrap เกี่ยวกับ",
    "th": "สำหรับ / เกี่ยวกับ",
    "thToZh": "对于",
    "sentenceZh": "老师让我们学习“对于”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “对于” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า samrap",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “สำหรับ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 103,
    "zh": "儿童",
    "pinyin": "ér tóng",
    "thaiPronunciation": "dek",
    "th": "เด็ก",
    "thToZh": "儿童",
    "sentenceZh": "老师让我们学习“儿童”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “儿童” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า dek",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “เด็ก”",
    "image": "🧒",
    "category": "HSK4"
  },
  {
    "id": 104,
    "zh": "而",
    "pinyin": "ér",
    "thaiPronunciation": "lae แต่",
    "th": "และ / แต่",
    "thToZh": "而",
    "sentenceZh": "老师让我们学习“而”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “而” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า lae",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “และ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 105,
    "zh": "发生",
    "pinyin": "fā shēng",
    "thaiPronunciation": "koet khuen",
    "th": "เกิดขึ้น",
    "thToZh": "发生",
    "sentenceZh": "老师让我们学习“发生”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “发生” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า koet khuen",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “เกิดขึ้น”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 106,
    "zh": "发展",
    "pinyin": "fā zhǎn",
    "thaiPronunciation": "phatthana",
    "th": "พัฒนา",
    "thToZh": "发展",
    "sentenceZh": "老师让我们学习“发展”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “发展” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า phatthana",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “พัฒนา”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 107,
    "zh": "法律",
    "pinyin": "fǎ lǜ",
    "thaiPronunciation": "kotmai",
    "th": "กฎหมาย",
    "thToZh": "法律",
    "sentenceZh": "老师让我们学习“法律”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “法律” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า kotmai",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “กฎหมาย”",
    "image": "⚖️",
    "category": "HSK4"
  },
  {
    "id": 108,
    "zh": "翻译",
    "pinyin": "fān yì",
    "thaiPronunciation": "plae phasa",
    "th": "แปลภาษา",
    "thToZh": "翻译",
    "sentenceZh": "老师让我们学习“翻译”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “翻译” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า plae phasa",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “แปลภาษา”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 109,
    "zh": "烦恼",
    "pinyin": "fán nǎo",
    "thaiPronunciation": "khwam kangwon กลุ้มใจ",
    "th": "ความกังวล / กลุ้มใจ",
    "thToZh": "烦恼",
    "sentenceZh": "老师让我们学习“烦恼”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “烦恼” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า khwam kangwon",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ความกังวล”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 110,
    "zh": "反对",
    "pinyin": "fǎn duì",
    "thaiPronunciation": "khatkhan",
    "th": "คัดค้าน",
    "thToZh": "反对",
    "sentenceZh": "老师让我们学习“反对”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “反对” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า khatkhan",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “คัดค้าน”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 111,
    "zh": "方法",
    "pinyin": "fāng fǎ",
    "thaiPronunciation": "withi",
    "th": "วิธี",
    "thToZh": "方法",
    "sentenceZh": "老师让我们学习“方法”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “方法” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า withi",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “วิธี”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 112,
    "zh": "方面",
    "pinyin": "fāng miàn",
    "thaiPronunciation": "dan แง่มุม",
    "th": "ด้าน / แง่มุม",
    "thToZh": "方面",
    "sentenceZh": "老师让我们学习“方面”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “方面” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า dan",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ด้าน”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 113,
    "zh": "方向",
    "pinyin": "fāng xiàng",
    "thaiPronunciation": "thitthang",
    "th": "ทิศทาง",
    "thToZh": "方向",
    "sentenceZh": "老师让我们学习“方向”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “方向” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า thitthang",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ทิศทาง”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 114,
    "zh": "房东",
    "pinyin": "fáng dōng",
    "thaiPronunciation": "chao khong ban เจ้าของห้องเช่า",
    "th": "เจ้าของบ้าน / เจ้าของห้องเช่า",
    "thToZh": "房东",
    "sentenceZh": "老师让我们学习“房东”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “房东” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า chao khong ban",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “เจ้าของบ้าน”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 115,
    "zh": "放弃",
    "pinyin": "fàng qì",
    "thaiPronunciation": "yom phae ละทิ้ง",
    "th": "ยอมแพ้ / ละทิ้ง",
    "thToZh": "放弃",
    "sentenceZh": "老师让我们学习“放弃”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “放弃” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า yom phae",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ยอมแพ้”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 116,
    "zh": "放暑假",
    "pinyin": "fàng shǔ jià",
    "thaiPronunciation": "ปิดเทอมฤดูร้อน",
    "th": "ปิดเทอมฤดูร้อน",
    "thToZh": "放暑假",
    "sentenceZh": "老师让我们学习“放暑假”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “放暑假” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า ปิดเทอมฤดูร้อน",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ปิดเทอมฤดูร้อน”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 117,
    "zh": "放松",
    "pinyin": "fàng sōng",
    "thaiPronunciation": "phonkhlai",
    "th": "ผ่อนคลาย",
    "thToZh": "放松",
    "sentenceZh": "老师让我们学习“放松”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “放松” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า phonkhlai",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ผ่อนคลาย”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 118,
    "zh": "份",
    "pinyin": "fèn",
    "thaiPronunciation": "chabap ส่วน ชุด",
    "th": "ฉบับ / ส่วน / ชุด",
    "thToZh": "份",
    "sentenceZh": "老师让我们学习“份”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “份” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า chabap",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ฉบับ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 119,
    "zh": "丰富",
    "pinyin": "fēng fù",
    "thaiPronunciation": "udom sombun หลากหลาย",
    "th": "อุดมสมบูรณ์ / หลากหลาย",
    "thToZh": "丰富",
    "sentenceZh": "老师让我们学习“丰富”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “丰富” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า udom sombun",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “อุดมสมบูรณ์”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 120,
    "zh": "否则",
    "pinyin": "fǒu zé",
    "thaiPronunciation": "มิฉะนั้น",
    "th": "มิฉะนั้น",
    "thToZh": "否则",
    "sentenceZh": "老师让我们学习“否则”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “否则” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า มิฉะนั้น",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “มิฉะนั้น”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 121,
    "zh": "符合",
    "pinyin": "fú hé",
    "thaiPronunciation": "sotkhlong ตรงตาม",
    "th": "สอดคล้อง / ตรงตาม",
    "thToZh": "符合",
    "sentenceZh": "老师让我们学习“符合”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “符合” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า sotkhlong",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “สอดคล้อง”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 122,
    "zh": "付款",
    "pinyin": "fù kuǎn",
    "thaiPronunciation": "chamra ngoen",
    "th": "ชำระเงิน",
    "thToZh": "付款",
    "sentenceZh": "老师让我们学习“付款”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “付款” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า chamra ngoen",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ชำระเงิน”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 123,
    "zh": "复印",
    "pinyin": "fù yìn",
    "thaiPronunciation": "ถ่ายเอกสาร",
    "th": "ถ่ายเอกสาร",
    "thToZh": "复印",
    "sentenceZh": "老师让我们学习“复印”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “复印” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า ถ่ายเอกสาร",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ถ่ายเอกสาร”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 124,
    "zh": "复杂",
    "pinyin": "fù zá",
    "thaiPronunciation": "ซับซ้อน",
    "th": "ซับซ้อน",
    "thToZh": "复杂",
    "sentenceZh": "老师让我们学习“复杂”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “复杂” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า ซับซ้อน",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ซับซ้อน”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 125,
    "zh": "富",
    "pinyin": "fù",
    "thaiPronunciation": "ร่ำรวย",
    "th": "ร่ำรวย",
    "thToZh": "富",
    "sentenceZh": "老师让我们学习“富”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “富” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า ร่ำรวย",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ร่ำรวย”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 126,
    "zh": "父亲",
    "pinyin": "fù qīn",
    "thaiPronunciation": "พ่อ",
    "th": "พ่อ",
    "thToZh": "父亲",
    "sentenceZh": "老师让我们学习“父亲”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “父亲” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า พ่อ",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “พ่อ”",
    "image": "👨",
    "category": "HSK4"
  },
  {
    "id": 127,
    "zh": "负责",
    "pinyin": "fù zé",
    "thaiPronunciation": "รับผิดชอบ",
    "th": "รับผิดชอบ",
    "thToZh": "负责",
    "sentenceZh": "老师让我们学习“负责”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “负责” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า รับผิดชอบ",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “รับผิดชอบ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 128,
    "zh": "改变",
    "pinyin": "gǎi biàn",
    "thaiPronunciation": "เปลี่ยนแปลง",
    "th": "เปลี่ยนแปลง",
    "thToZh": "改变",
    "sentenceZh": "老师让我们学习“改变”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “改变” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า เปลี่ยนแปลง",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “เปลี่ยนแปลง”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 129,
    "zh": "干杯",
    "pinyin": "gān bēi",
    "thaiPronunciation": "ชนแก้ว",
    "th": "ชนแก้ว",
    "thToZh": "干杯",
    "sentenceZh": "老师让我们学习“干杯”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “干杯” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า ชนแก้ว",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ชนแก้ว”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 130,
    "zh": "感动",
    "pinyin": "gǎn dòng",
    "thaiPronunciation": "ซาบซึ้ง ทำให้ประทับใจ",
    "th": "ซาบซึ้ง / ทำให้ประทับใจ",
    "thToZh": "感动",
    "sentenceZh": "老师让我们学习“感动”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “感动” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า ซาบซึ้ง",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ซาบซึ้ง”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 131,
    "zh": "感觉",
    "pinyin": "gǎn jué",
    "thaiPronunciation": "ความรู้สึก รู้สึก",
    "th": "ความรู้สึก / รู้สึก",
    "thToZh": "感觉",
    "sentenceZh": "老师让我们学习“感觉”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “感觉” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า ความรู้สึก",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ความรู้สึก”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 132,
    "zh": "感情",
    "pinyin": "gǎn qíng",
    "thaiPronunciation": "ความรู้สึก ความสัมพันธ์",
    "th": "ความรู้สึก / ความสัมพันธ์",
    "thToZh": "感情",
    "sentenceZh": "老师让我们学习“感情”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “感情” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า ความรู้สึก",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ความรู้สึก”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 133,
    "zh": "感谢",
    "pinyin": "gǎn xiè",
    "thaiPronunciation": "ขอบคุณ",
    "th": "ขอบคุณ",
    "thToZh": "感谢",
    "sentenceZh": "老师让我们学习“感谢”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “感谢” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า ขอบคุณ",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ขอบคุณ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 134,
    "zh": "敢",
    "pinyin": "gǎn",
    "thaiPronunciation": "กล้า",
    "th": "กล้า",
    "thToZh": "敢",
    "sentenceZh": "老师让我们学习“敢”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “敢” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า กล้า",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “กล้า”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 135,
    "zh": "赶",
    "pinyin": "gǎn",
    "thaiPronunciation": "รีบ ตามทัน",
    "th": "รีบ / ตามทัน",
    "thToZh": "赶",
    "sentenceZh": "老师让我们学习“赶”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “赶” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า รีบ",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “รีบ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 136,
    "zh": "干",
    "pinyin": "gàn",
    "thaiPronunciation": "ทำงาน ทำ",
    "th": "ทำงาน / ทำ",
    "thToZh": "干",
    "sentenceZh": "老师让我们学习“干”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “干” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า ทำงาน",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ทำงาน”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 137,
    "zh": "刚",
    "pinyin": "gāng",
    "thaiPronunciation": "เพิ่ง พึ่งจะ",
    "th": "เพิ่ง / พึ่งจะ",
    "thToZh": "刚",
    "sentenceZh": "老师让我们学习“刚”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “刚” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า เพิ่ง",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “เพิ่ง”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 138,
    "zh": "高速公路",
    "pinyin": "gāo sù gōng lù",
    "thaiPronunciation": "ทางด่วน ทางหลวง",
    "th": "ทางด่วน / ทางหลวง",
    "thToZh": "高速公路",
    "sentenceZh": "老师让我们学习“高速公路”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “高速公路” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า ทางด่วน",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ทางด่วน”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 139,
    "zh": "胳膊",
    "pinyin": "gē bo",
    "thaiPronunciation": "แขน",
    "th": "แขน",
    "thToZh": "胳膊",
    "sentenceZh": "老师让我们学习“胳膊”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “胳膊” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า แขน",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “แขน”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 140,
    "zh": "各",
    "pinyin": "gè",
    "thaiPronunciation": "แต่ละ",
    "th": "แต่ละ",
    "thToZh": "各",
    "sentenceZh": "老师让我们学习“各”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “各” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า แต่ละ",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “แต่ละ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 141,
    "zh": "公里",
    "pinyin": "gōng lǐ",
    "thaiPronunciation": "กิโลเมตร",
    "th": "กิโลเมตร",
    "thToZh": "公里",
    "sentenceZh": "老师让我们学习“公里”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “公里” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า กิโลเมตร",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “กิโลเมตร”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 142,
    "zh": "功夫",
    "pinyin": "gōng fu",
    "thaiPronunciation": "ทักษะ กังฟู",
    "th": "ทักษะ / กังฟู",
    "thToZh": "功夫",
    "sentenceZh": "老师让我们学习“功夫”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “功夫” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า ทักษะ",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ทักษะ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 143,
    "zh": "工资",
    "pinyin": "gōng zī",
    "thaiPronunciation": "เงินเดือน",
    "th": "เงินเดือน",
    "thToZh": "工资",
    "sentenceZh": "老师让我们学习“工资”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “工资” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า เงินเดือน",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “เงินเดือน”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 144,
    "zh": "共同",
    "pinyin": "gòng tóng",
    "thaiPronunciation": "ร่วมกัน",
    "th": "ร่วมกัน",
    "thToZh": "共同",
    "sentenceZh": "老师让我们学习“共同”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “共同” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า ร่วมกัน",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ร่วมกัน”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 145,
    "zh": "够",
    "pinyin": "gòu",
    "thaiPronunciation": "พอ",
    "th": "พอ",
    "thToZh": "够",
    "sentenceZh": "老师让我们学习“够”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “够” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า พอ",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “พอ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 146,
    "zh": "购物",
    "pinyin": "gòu wù",
    "thaiPronunciation": "ช้อปปิ้ง",
    "th": "ช้อปปิ้ง",
    "thToZh": "购物",
    "sentenceZh": "老师让我们学习“购物”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “购物” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า ช้อปปิ้ง",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ช้อปปิ้ง”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 147,
    "zh": "估计",
    "pinyin": "gū jì",
    "thaiPronunciation": "คาดว่า praman",
    "th": "คาดว่า / ประมาณ",
    "thToZh": "估计",
    "sentenceZh": "老师让我们学习“估计”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “估计” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า คาดว่า",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “คาดว่า”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 148,
    "zh": "鼓励",
    "pinyin": "gǔ lì",
    "thaiPronunciation": "ให้กำลังใจ สนับสนุน",
    "th": "ให้กำลังใจ / สนับสนุน",
    "thToZh": "鼓励",
    "sentenceZh": "老师让我们学习“鼓励”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “鼓励” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า ให้กำลังใจ",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ให้กำลังใจ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 149,
    "zh": "故意",
    "pinyin": "gù yì",
    "thaiPronunciation": "ตั้งใจ จงใจ",
    "th": "ตั้งใจ / จงใจ",
    "thToZh": "故意",
    "sentenceZh": "老师让我们学习“故意”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “故意” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า ตั้งใจ",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ตั้งใจ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 150,
    "zh": "顾客",
    "pinyin": "gù kè",
    "thaiPronunciation": "ลูกค้า",
    "th": "ลูกค้า",
    "thToZh": "顾客",
    "sentenceZh": "老师让我们学习“顾客”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “顾客” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า ลูกค้า",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ลูกค้า”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 151,
    "zh": "挂",
    "pinyin": "guà",
    "thaiPronunciation": "แขวน วางสาย",
    "th": "แขวน / วางสาย",
    "thToZh": "挂",
    "sentenceZh": "老师让我们学习“挂”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “挂” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า แขวน",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “แขวน”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 152,
    "zh": "关键",
    "pinyin": "guān jiàn",
    "thaiPronunciation": "กุญแจสำคัญ",
    "th": "กุญแจสำคัญ",
    "thToZh": "关键",
    "sentenceZh": "老师让我们学习“关键”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “关键” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า กุญแจสำคัญ",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “กุญแจสำคัญ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 153,
    "zh": "观众",
    "pinyin": "guān zhòng",
    "thaiPronunciation": "ผู้ชม",
    "th": "ผู้ชม",
    "thToZh": "观众",
    "sentenceZh": "老师让我们学习“观众”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “观众” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า ผู้ชม",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ผู้ชม”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 154,
    "zh": "管理",
    "pinyin": "guǎn lǐ",
    "thaiPronunciation": "chatkan บริหาร",
    "th": "จัดการ / บริหาร",
    "thToZh": "管理",
    "sentenceZh": "老师让我们学习“管理”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “管理” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า chatkan",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “จัดการ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 155,
    "zh": "光",
    "pinyin": "guāng",
    "thaiPronunciation": "แสง เพียงแต่",
    "th": "แสง / เพียงแต่",
    "thToZh": "光",
    "sentenceZh": "老师让我们学习“光”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “光” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า แสง",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “แสง”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 156,
    "zh": "广播",
    "pinyin": "guǎng bō",
    "thaiPronunciation": "กระจายเสียง",
    "th": "กระจายเสียง",
    "thToZh": "广播",
    "sentenceZh": "老师让我们学习“广播”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “广播” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า กระจายเสียง",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “กระจายเสียง”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 157,
    "zh": "广告",
    "pinyin": "guǎng gào",
    "thaiPronunciation": "โฆษณา",
    "th": "โฆษณา",
    "thToZh": "广告",
    "sentenceZh": "老师让我们学习“广告”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “广告” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า โฆษณา",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “โฆษณา”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 158,
    "zh": "逛",
    "pinyin": "guàng",
    "thaiPronunciation": "เดินเล่น เดินเที่ยว",
    "th": "เดินเล่น / เดินเที่ยว",
    "thToZh": "逛",
    "sentenceZh": "老师让我们学习“逛”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “逛” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า เดินเล่น",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “เดินเล่น”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 159,
    "zh": "规定",
    "pinyin": "guī dìng",
    "thaiPronunciation": "กำหนด กฎระเบียบ",
    "th": "กำหนด / กฎระเบียบ",
    "thToZh": "规定",
    "sentenceZh": "老师让我们学习“规定”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “规定” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า กำหนด",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “กำหนด”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 160,
    "zh": "国籍",
    "pinyin": "guó jí",
    "thaiPronunciation": "สัญชาติ",
    "th": "สัญชาติ",
    "thToZh": "国籍",
    "sentenceZh": "老师让我们学习“国籍”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “国籍” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า สัญชาติ",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “สัญชาติ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 161,
    "zh": "国际",
    "pinyin": "guó jì",
    "thaiPronunciation": "นานาชาติ",
    "th": "นานาชาติ",
    "thToZh": "国际",
    "sentenceZh": "老师让我们学习“国际”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “国际” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า นานาชาติ",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “นานาชาติ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 162,
    "zh": "果汁",
    "pinyin": "guǒ zhī",
    "thaiPronunciation": "น้ำผลไม้",
    "th": "น้ำผลไม้",
    "thToZh": "果汁",
    "sentenceZh": "老师让我们学习“果汁”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “果汁” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า น้ำผลไม้",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “น้ำผลไม้”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 163,
    "zh": "过程",
    "pinyin": "guò chéng",
    "thaiPronunciation": "กระบวนการ",
    "th": "กระบวนการ",
    "thToZh": "过程",
    "sentenceZh": "老师让我们学习“过程”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “过程” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า กระบวนการ",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “กระบวนการ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 164,
    "zh": "海洋",
    "pinyin": "hǎi yáng",
    "thaiPronunciation": "มหาสมุทร",
    "th": "มหาสมุทร",
    "thToZh": "海洋",
    "sentenceZh": "老师让我们学习“海洋”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “海洋” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า มหาสมุทร",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “มหาสมุทร”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 165,
    "zh": "害羞",
    "pinyin": "hài xiū",
    "thaiPronunciation": "ขี้อาย",
    "th": "ขี้อาย",
    "thToZh": "害羞",
    "sentenceZh": "老师让我们学习“害羞”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “害羞” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า ขี้อาย",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ขี้อาย”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 166,
    "zh": "寒假",
    "pinyin": "hán jià",
    "thaiPronunciation": "ปิดเทอมฤดูหนาว",
    "th": "ปิดเทอมฤดูหนาว",
    "thToZh": "寒假",
    "sentenceZh": "老师让我们学习“寒假”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “寒假” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า ปิดเทอมฤดูหนาว",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ปิดเทอมฤดูหนาว”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 167,
    "zh": "汗",
    "pinyin": "hàn",
    "thaiPronunciation": "เหงื่อ",
    "th": "เหงื่อ",
    "thToZh": "汗",
    "sentenceZh": "老师让我们学习“汗”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “汗” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า เหงื่อ",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “เหงื่อ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 168,
    "zh": "航班",
    "pinyin": "háng bān",
    "thaiPronunciation": "เที่ยวบิน",
    "th": "เที่ยวบิน",
    "thToZh": "航班",
    "sentenceZh": "老师让我们学习“航班”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “航班” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า เที่ยวบิน",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “เที่ยวบิน”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 169,
    "zh": "好处",
    "pinyin": "hǎo chu",
    "thaiPronunciation": "ข้อดี ประโยชน์",
    "th": "ข้อดี / ประโยชน์",
    "thToZh": "好处",
    "sentenceZh": "老师让我们学习“好处”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “好处” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า ข้อดี",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ข้อดี”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 170,
    "zh": "好像",
    "pinyin": "hǎo xiàng",
    "thaiPronunciation": "เหมือนว่า",
    "th": "เหมือนว่า",
    "thToZh": "好像",
    "sentenceZh": "老师让我们学习“好像”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “好像” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า เหมือนว่า",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “เหมือนว่า”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 171,
    "zh": "号码",
    "pinyin": "hào mǎ",
    "thaiPronunciation": "หมายเลข",
    "th": "หมายเลข",
    "thToZh": "号码",
    "sentenceZh": "老师让我们学习“号码”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “号码” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า หมายเลข",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “หมายเลข”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 172,
    "zh": "合格",
    "pinyin": "hé gé",
    "thaiPronunciation": "ผ่านมาตรฐาน",
    "th": "ผ่านมาตรฐาน",
    "thToZh": "合格",
    "sentenceZh": "老师让我们学习“合格”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “合格” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า ผ่านมาตรฐาน",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ผ่านมาตรฐาน”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 173,
    "zh": "合适",
    "pinyin": "hé shì",
    "thaiPronunciation": "เหมาะสม",
    "th": "เหมาะสม",
    "thToZh": "合适",
    "sentenceZh": "老师让我们学习“合适”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “合适” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า เหมาะสม",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “เหมาะสม”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 174,
    "zh": "盒子",
    "pinyin": "hé zi",
    "thaiPronunciation": "กล่อง",
    "th": "กล่อง",
    "thToZh": "盒子",
    "sentenceZh": "老师让我们学习“盒子”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “盒子” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า กล่อง",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “กล่อง”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 175,
    "zh": "厚",
    "pinyin": "hòu",
    "thaiPronunciation": "หนา",
    "th": "หนา",
    "thToZh": "厚",
    "sentenceZh": "老师让我们学习“厚”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “厚” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า หนา",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “หนา”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 176,
    "zh": "后悔",
    "pinyin": "hòu huǐ",
    "thaiPronunciation": "เสียใจภายหลัง",
    "th": "เสียใจภายหลัง",
    "thToZh": "后悔",
    "sentenceZh": "老师让我们学习“后悔”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “后悔” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า เสียใจภายหลัง",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “เสียใจภายหลัง”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 177,
    "zh": "互联网",
    "pinyin": "hù lián wǎng",
    "thaiPronunciation": "อินเทอร์เน็ต",
    "th": "อินเทอร์เน็ต",
    "thToZh": "互联网",
    "sentenceZh": "老师让我们学习“互联网”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “互联网” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า อินเทอร์เน็ต",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “อินเทอร์เน็ต”",
    "image": "🌐",
    "category": "HSK4"
  },
  {
    "id": 178,
    "zh": "互相",
    "pinyin": "hù xiāng",
    "thaiPronunciation": "ซึ่งกันและกัน",
    "th": "ซึ่งกันและกัน",
    "thToZh": "互相",
    "sentenceZh": "老师让我们学习“互相”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “互相” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า ซึ่งกันและกัน",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ซึ่งกันและกัน”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 179,
    "zh": "护士",
    "pinyin": "hù shi",
    "thaiPronunciation": "พยาบาล",
    "th": "พยาบาล",
    "thToZh": "护士",
    "sentenceZh": "老师让我们学习“护士”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “护士” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า พยาบาล",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “พยาบาล”",
    "image": "🩺",
    "category": "HSK4"
  },
  {
    "id": 180,
    "zh": "怀疑",
    "pinyin": "huái yí",
    "thaiPronunciation": "สงสัย",
    "th": "สงสัย",
    "thToZh": "怀疑",
    "sentenceZh": "老师让我们学习“怀疑”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “怀疑” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า สงสัย",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “สงสัย”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 181,
    "zh": "回忆",
    "pinyin": "huí yì",
    "thaiPronunciation": "ความทรงจำ ระลึกถึง",
    "th": "ความทรงจำ / ระลึกถึง",
    "thToZh": "回忆",
    "sentenceZh": "老师让我们学习“回忆”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “回忆” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า ความทรงจำ",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ความทรงจำ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 182,
    "zh": "活动",
    "pinyin": "huó dòng",
    "thaiPronunciation": "กิจกรรม",
    "th": "กิจกรรม",
    "thToZh": "活动",
    "sentenceZh": "老师让我们学习“活动”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “活动” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า กิจกรรม",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “กิจกรรม”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 183,
    "zh": "活泼",
    "pinyin": "huó po",
    "thaiPronunciation": "ร่าเริง",
    "th": "ร่าเริง",
    "thToZh": "活泼",
    "sentenceZh": "老师让我们学习“活泼”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “活泼” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า ร่าเริง",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ร่าเริง”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 184,
    "zh": "火",
    "pinyin": "huǒ",
    "thaiPronunciation": "ไฟ",
    "th": "ไฟ",
    "thToZh": "火",
    "sentenceZh": "老师让我们学习“火”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “火” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า ไฟ",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ไฟ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 185,
    "zh": "获得",
    "pinyin": "huò dé",
    "thaiPronunciation": "ได้รับ",
    "th": "ได้รับ",
    "thToZh": "获得",
    "sentenceZh": "老师让我们学习“获得”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “获得” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า ได้รับ",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ได้รับ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 186,
    "zh": "基础",
    "pinyin": "jī chǔ",
    "thaiPronunciation": "พื้นฐาน",
    "th": "พื้นฐาน",
    "thToZh": "基础",
    "sentenceZh": "老师让我们学习“基础”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “基础” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า พื้นฐาน",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “พื้นฐาน”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 187,
    "zh": "激动",
    "pinyin": "jī dòng",
    "thaiPronunciation": "ตื่นเต้น กระตุ้น",
    "th": "ตื่นเต้น / กระตุ้น",
    "thToZh": "激动",
    "sentenceZh": "老师让我们学习“激动”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “激动” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า ตื่นเต้น",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ตื่นเต้น”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 188,
    "zh": "积极",
    "pinyin": "jī jí",
    "thaiPronunciation": "กระตือรือร้น เชิงบวก",
    "th": "กระตือรือร้น / เชิงบวก",
    "thToZh": "积极",
    "sentenceZh": "老师让我们学习“积极”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “积极” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า กระตือรือร้น",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “กระตือรือร้น”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 189,
    "zh": "积累",
    "pinyin": "jī lěi",
    "thaiPronunciation": "สะสม",
    "th": "สะสม",
    "thToZh": "积累",
    "sentenceZh": "老师让我们学习“积累”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “积累” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า สะสม",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “สะสม”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 190,
    "zh": "即使",
    "pinyin": "jí shǐ",
    "thaiPronunciation": "แม้ว่า",
    "th": "แม้ว่า",
    "thToZh": "即使",
    "sentenceZh": "老师让我们学习“即使”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “即使” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า แม้ว่า",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “แม้ว่า”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 191,
    "zh": "及时",
    "pinyin": "jí shí",
    "thaiPronunciation": "ทันเวลา",
    "th": "ทันเวลา",
    "thToZh": "及时",
    "sentenceZh": "老师让我们学习“及时”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “及时” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า ทันเวลา",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ทันเวลา”",
    "image": "⏰",
    "category": "HSK4"
  },
  {
    "id": 192,
    "zh": "寄",
    "pinyin": "jì",
    "thaiPronunciation": "ส่งไปรษณีย์",
    "th": "ส่งไปรษณีย์",
    "thToZh": "寄",
    "sentenceZh": "老师让我们学习“寄”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “寄” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า ส่งไปรษณีย์",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ส่งไปรษณีย์”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 193,
    "zh": "技术",
    "pinyin": "jì shù",
    "thaiPronunciation": "เทคโนโลยี ทักษะ",
    "th": "เทคโนโลยี / ทักษะ",
    "thToZh": "技术",
    "sentenceZh": "老师让我们学习“技术”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “技术” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า เทคโนโลยี",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “เทคโนโลยี”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 194,
    "zh": "既然",
    "pinyin": "jì rán",
    "thaiPronunciation": "ในเมื่อ",
    "th": "ในเมื่อ",
    "thToZh": "既然",
    "sentenceZh": "老师让我们学习“既然”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “既然” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า ในเมื่อ",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ในเมื่อ”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 195,
    "zh": "继续",
    "pinyin": "jì xù",
    "thaiPronunciation": "ต่อเนื่อง ดำเนินต่อ",
    "th": "ต่อเนื่อง / ดำเนินต่อ",
    "thToZh": "继续",
    "sentenceZh": "老师让我们学习“继续”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “继续” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า ต่อเนื่อง",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ต่อเนื่อง”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 196,
    "zh": "计划",
    "pinyin": "jì huà",
    "thaiPronunciation": "แผน wang phaen",
    "th": "แผน / วางแผน",
    "thToZh": "计划",
    "sentenceZh": "老师让我们学习“计划”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “计划” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า แผน",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “แผน”",
    "image": "🀄",
    "category": "HSK4"
  },
  {
    "id": 197,
    "zh": "记者",
    "pinyin": "jì zhě",
    "thaiPronunciation": "นักข่าว",
    "th": "นักข่าว",
    "thToZh": "记者",
    "sentenceZh": "老师让我们学习“记者”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “记者” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า นักข่าว",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “นักข่าว”",
    "image": "📰",
    "category": "HSK4"
  },
  {
    "id": 198,
    "zh": "加班",
    "pinyin": "jiā bān",
    "thaiPronunciation": "ทำงานล่วงเวลา",
    "th": "ทำงานล่วงเวลา",
    "thToZh": "加班",
    "sentenceZh": "老师让我们学习“加班”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “加班” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า ทำงานล่วงเวลา",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ทำงานล่วงเวลา”",
    "image": "⏰",
    "category": "HSK4"
  },
  {
    "id": 199,
    "zh": "加油站",
    "pinyin": "jiā yóu zhàn",
    "thaiPronunciation": "ปั๊มน้ำมัน",
    "th": "ปั๊มน้ำมัน",
    "thToZh": "加油站",
    "sentenceZh": "老师让我们学习“加油站”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “加油站” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า ปั๊มน้ำมัน",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “ปั๊มน้ำมัน”",
    "image": "⛽",
    "category": "HSK4"
  },
  {
    "id": 200,
    "zh": "家具",
    "pinyin": "jiā jù",
    "thaiPronunciation": "เฟอร์นิเจอร์",
    "th": "เฟอร์นิเจอร์",
    "thToZh": "家具",
    "sentenceZh": "老师让我们学习“家具”这个词。",
    "sentencePinyin": "lǎo shī ràng wǒ men xué xí “家具” zhè ge cí",
    "sentenceThaiPronunciation": "ครูให้พวกเราเรียนคำว่า เฟอร์นิเจอร์",
    "sentenceTh": "ครูให้พวกเราเรียนคำว่า “เฟอร์นิเจอร์”",
    "image": "🀄",
    "category": "HSK4"
  }
];
